Repository DependencyTrack/hyades-apiserver, pull requests merged in 2023-11, with the labels that each got.

#398 Bump Redpanda to `v23.2.13`
  src/test/java/org/dependencytrack/event/kafka/KafkaStreamsPostgresTest.java
  src/test/java/org/dependencytrack/event/kafka/KafkaStreamsTest.java
Labels: dependencies, docker

#412 Add null check on publishedAt
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/test/java/org/dependencytrack/persistence/QueryManagerTest.java
Labels: bug

#413 Fix inconsistent `purlCoordinates`
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
Labels: bug

#416 Send integrity meta events only for supported types
  src/main/java/org/dependencytrack/tasks/IntegrityMetaInitializerTask.java
  src/test/java/org/dependencytrack/tasks/IntegrityMetaInitializerTaskTest.java
Labels: bug

#414 Fix BOM validation failing for spec versions lower than 1.5
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/resources/unit/bom-schema1.0.xml
  src/test/resources/unit/bom-schema1.1.xml
  src/test/resources/unit/bom-schema1.2.json
  src/test/resources/unit/bom-schema1.2.xml
  src/test/resources/unit/bom-schema1.3.json
  src/test/resources/unit/bom-schema1.3.xml
  src/test/resources/unit/bom-schema1.4.json
  src/test/resources/unit/bom-schema1.4.xml
  src/test/resources/unit/bom-schema1.5.json
  src/test/resources/unit/bom-schema1.5.xml
Labels: bug

#415 Downgrade Jetty Maven Plugin to `10.x`
  .github/dependabot.yml
  pom.xml
Labels: bug

#419 Address performance regression during BOM processing
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: bug

#422 Fix FK violation during BOM processing
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/persistence/ComponentQueryManagerTest.java
  src/test/java/org/dependencytrack/persistence/ProjectQueryManagerTest.java
Labels: bug

#423 Diff changes made by scanners to existing vulnerabilities
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/util/PersistenceUtil.java
  src/test/java/org/dependencytrack/util/PersistenceUtilTest.java
Labels: enhancement

#425 Fix singleton events not being untracked upon unexpected failures
  src/main/java/org/dependencytrack/tasks/EpssMirrorTask.java
  src/main/java/org/dependencytrack/tasks/NistMirrorTask.java
Labels: bug

#428 Fix component published date not being returned when no integrity analysis exists for it
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/test/java/org/dependencytrack/persistence/QueryManagerTest.java
Labels: bug

#427 Fix BOM processing failure when BOM contains services
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-service.json
Labels: bug

#431 Support more `Component` fields in `is_dependency_of` and `depends_on` CEL functions
  src/main/java/org/dependencytrack/policy/cel/CelPolicyLibrary.java
Labels: enhancement

#434 Integrity Analysis on Bom Upload when integrity metadata already exists
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/event/IntegrityAnalysisEvent.java
  src/main/java/org/dependencytrack/event/kafka/componentmeta/IntegrityCheck.java
  src/main/java/org/dependencytrack/event/kafka/componentmeta/SupportedMetaHandler.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/IntegrityAnalysisTask.java
  src/test/java/org/dependencytrack/event/kafka/componentmeta/SupportedMetaHandlerTest.java
  src/test/java/org/dependencytrack/tasks/IntegrityAnalysisTaskTest.java
Labels: enhancement

#433 hash check fixed to fail on even a single hash mismatch
  src/main/java/org/dependencytrack/event/kafka/componentmeta/IntegrityCheck.java
Labels: bug

#442 Use Liquibase for database migrations
  pom.xml
  src/main/java/alpine/server/persistence/PersistenceManagerFactory.java
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/persistence/migration/MigrationInitializer.java
  src/main/java/org/dependencytrack/persistence/migration/change/RenameForeignKeysChange.java
  src/main/java/org/dependencytrack/persistence/migration/change/RenameNumberedIndexesChange.java
  src/main/resources/migration/changelog-main.xml
  src/main/resources/migration/changelog-v5.3.0.xml
  src/main/webapp/WEB-INF/web.xml
  src/test/java/org/dependencytrack/persistence/migration/MigrationInitializerTest.java
  src/test/java/org/dependencytrack/persistence/migration/change/RenameForeignKeysChangeTest.java
  src/test/java/org/dependencytrack/persistence/migration/change/RenameNumberedIndexesChangeTest.java
  src/test/resources/migration/custom/RenameForeignKeysChangeTest-changelog.xml
  src/test/resources/migration/custom/RenameNumberedIndexesChangeTest-changelog.xml
  src/test/resources/migration/custom/schema-v5.2.0-postgresql.sql
Labels: enhancement

#448 Add `now` variable for time comparisons in CEL expressions
  src/main/java/org/dependencytrack/policy/cel/CelPolicyEngine.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyLibrary.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyEngineTest.java
Labels: enhancement

#451 Fix resource leak in `CelPolicyLibrary#matchesVersionDistance`
  src/main/java/org/dependencytrack/policy/cel/CelPolicyLibrary.java
Labels: bug

#449 Additions to Liquibase integration
  src/main/java/org/dependencytrack/persistence/ShedlockInitializer.java
  src/main/java/org/dependencytrack/persistence/StoredProcedureInitializer.java
  src/main/java/org/dependencytrack/persistence/migration/MigrationInitializer.java
  src/main/java/org/dependencytrack/persistence/migration/change/v530/RenameForeignKeysChange.java
  src/main/java/org/dependencytrack/persistence/migration/change/v530/RenameNumberedIndexesChange.java
  src/main/resources/migration/changelog-main.xml
  src/main/resources/migration/changelog-procedures.xml
  src/main/resources/migration/changelog-v5.3.0.xml
  src/main/resources/migration/procedures/function_calc-risk-score.sql
  src/main/resources/migration/procedures/function_calc-severity.sql
  src/main/resources/migration/procedures/function_cvssv2-to-severity.sql
  src/main/resources/migration/procedures/function_cvssv3-to-severity.sql
  src/main/resources/migration/procedures/procedure_update-component-metrics.sql
  src/main/resources/migration/procedures/procedure_update-portfolio-metrics.sql
  src/main/resources/migration/procedures/procedure_update-project-metrics.sql
  src/main/resources/shedlock.sql
  src/main/resources/storedprocs-postgres.sql
  src/main/webapp/WEB-INF/web.xml
  src/test/java/org/dependencytrack/AbstractPostgresEnabledTest.java
  src/test/java/org/dependencytrack/TestUtil.java
  src/test/java/org/dependencytrack/persistence/migration/change/v530/RenameForeignKeysChangeTest.java
  src/test/java/org/dependencytrack/persistence/migration/change/v530/RenameNumberedIndexesChangeTest.java
  src/test/java/org/dependencytrack/tasks/WorkflowStateCleanupTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/AbstractMetricsUpdateTaskTest.java
  src/test/resources/migration/custom/RenameForeignKeysChangeTest-changelog.xml
  src/test/resources/migration/custom/RenameNumberedIndexesChangeTest-changelog.xml
Labels: enhancement

#454 Rename package `org.hyades` to `org.dependencytrack`
  src/main/java/org/dependencytrack/event/ComponentRepositoryMetaAnalysisEvent.java
  src/main/java/org/dependencytrack/event/kafka/KafkaEventConverter.java
  src/main/java/org/dependencytrack/event/kafka/KafkaEventHeaders.java
  src/main/java/org/dependencytrack/event/kafka/KafkaStreamsTopologyFactory.java
  src/main/java/org/dependencytrack/event/kafka/KafkaTopics.java
  src/main/java/org/dependencytrack/event/kafka/componentmeta/AbstractMetaHandler.java
  src/main/java/org/dependencytrack/event/kafka/componentmeta/HandlerFactory.java
  src/main/java/org/dependencytrack/event/kafka/componentmeta/IntegrityCheck.java
  src/main/java/org/dependencytrack/event/kafka/componentmeta/SupportedMetaHandler.java
  src/main/java/org/dependencytrack/event/kafka/componentmeta/UnSupportedMetaHandler.java
  src/main/java/org/dependencytrack/event/kafka/processor/DelayedBomProcessedNotificationProcessor.java
  src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
  src/main/java/org/dependencytrack/event/kafka/processor/RepositoryMetaResultProcessor.java
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/model/VulnerabilityScan.java
  src/main/java/org/dependencytrack/notification/vo/ProjectVulnAnalysisComplete.java
  src/main/java/org/dependencytrack/parser/dependencytrack/ModelConverterCdxToVuln.java
  src/main/java/org/dependencytrack/parser/dependencytrack/NotificationModelConverter.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyLibrary.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/IntegrityMetaInitializerTask.java
  src/main/java/org/dependencytrack/tasks/RepositoryMetaAnalyzerTask.java
  src/main/java/org/dependencytrack/util/NotificationUtil.java
  src/main/proto/org/dependencytrack/notification/v1/notification.proto
  src/main/proto/org/dependencytrack/repometaanalysis/v1/repo_meta_analysis.proto
  src/main/proto/org/dependencytrack/vulnanalysis/v1/vuln_analysis.proto
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/event/kafka/KafkaStreamsDelayedBomProcessedNotificationTest.java
  src/test/java/org/dependencytrack/event/kafka/KafkaStreamsPostgresTest.java
  src/test/java/org/dependencytrack/event/kafka/KafkaStreamsTopologyTest.java
  src/test/java/org/dependencytrack/event/kafka/componentmeta/HandlerFactoryTest.java
  src/test/java/org/dependencytrack/event/kafka/componentmeta/SupportedMetaHandlerTest.java
  src/test/java/org/dependencytrack/event/kafka/componentmeta/UnSupportedMetaHandlerTest.java
  src/test/java/org/dependencytrack/event/kafka/processor/RepositoryMetaResultProcessorTest.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/event/kafka/serialization/KafkaProtobufSerdeTest.java
  src/test/java/org/dependencytrack/parser/dependencytrack/ModelConverterCdxToVulnTest.java
  src/test/java/org/dependencytrack/parser/dependencytrack/NotificationModelConverterTest.java
  src/test/java/org/dependencytrack/policy/PolicyEngineTest.java
  src/test/java/org/dependencytrack/resources/v1/AnalysisResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ViolationAnalysisResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: enhancement

#456 Remove unused code
  .idea/runConfigurations/Build API Server Image.run.xml
  pom.xml
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/event/VulnDbSyncEvent.java
  src/main/java/org/dependencytrack/exception/PolicyException.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/parser/vulndb/ModelConverter.java
  src/main/java/org/dependencytrack/parser/vulndb/VulnDbClient.java
  src/main/java/org/dependencytrack/parser/vulndb/VulnDbParser.java
  src/main/java/org/dependencytrack/parser/vulndb/model/ApiObject.java
  src/main/java/org/dependencytrack/parser/vulndb/model/Author.java
  src/main/java/org/dependencytrack/parser/vulndb/model/Classification.java
  src/main/java/org/dependencytrack/parser/vulndb/model/Cpe.java
  src/main/java/org/dependencytrack/parser/vulndb/model/CvssV2Metric.java
  src/main/java/org/dependencytrack/parser/vulndb/model/CvssV3Metric.java
  src/main/java/org/dependencytrack/parser/vulndb/model/ExternalReference.java
  src/main/java/org/dependencytrack/parser/vulndb/model/ExternalText.java
  src/main/java/org/dependencytrack/parser/vulndb/model/NvdAdditionalInfo.java
  src/main/java/org/dependencytrack/parser/vulndb/model/Product.java
  src/main/java/org/dependencytrack/parser/vulndb/model/Results.java
  src/main/java/org/dependencytrack/parser/vulndb/model/Status.java
  src/main/java/org/dependencytrack/parser/vulndb/model/Vendor.java
  src/main/java/org/dependencytrack/parser/vulndb/model/Version.java
  src/main/java/org/dependencytrack/parser/vulndb/model/Vulnerability.java
  src/main/java/org/dependencytrack/tasks/TaskScheduler.java
  src/main/java/org/dependencytrack/tasks/VulnDbSyncTask.java
  src/main/java/org/dependencytrack/util/RoundRobinAccessor.java
  src/main/java/org/dependencytrack/util/XmlUtil.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/event/VulnDbSyncEventTest.java
  src/test/java/org/dependencytrack/util/RoundRobinAccessorTest.java
Labels: enhancement

#455 Add `vers` range validation before compilation
  src/main/java/org/dependencytrack/policy/cel/CelPolicyScriptHost.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyScriptVisitor.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyScriptHostTest.java
Labels: enhancement
