Repository DependencyTrack/hyades-apiserver, pull requests merged in 2023-10, with the labels that each got.

#357 Fix repo meta and vuln analysis tasks not considering projects with `active=null`
  src/main/java/org/dependencytrack/tasks/RepositoryMetaAnalyzerTask.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
  src/test/java/org/dependencytrack/tasks/RepositoryMetaAnalyzerTaskTest.java
  src/test/java/org/dependencytrack/tasks/VulnerabilityAnalysisTaskTest.java
Labels: bug

#362 port change for jsonignore on transient field
  src/main/java/org/dependencytrack/model/Project.java
Labels: bug

#363 Fix NPE during BOM processing when component doesn't have a PURL
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-no-purl.json
Labels: bug

#368 Port cyclonedx vex importer change from upstream
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXVexImporter.java
Labels: enhancement

#367 Added transient List of ProjectVersions and set Metrics in Project
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/model/ProjectVersion.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: enhancement

#373 Allow operator and violation when creating policy resource
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java
Labels: enhancement

#365 Fix NullPointerException when checking for existence of projects without version - port upstream fix
  src/main/java/org/dependencytrack/persistence/ProjectQueryFilterBuilder.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/ServiceComponentQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: bug

#364 Add support for custom license resolution by name
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-custom-license.json
Labels: enhancement

#370 Move `scripts` directory; Use standard directory for IntelliJ run configurations; Add project icon
  .dockerignore
  .gitignore
  .idea/icon.svg
  .idea/runConfigurations/Build API Server Image.run.xml
  .idea/runConfigurations/Build API Server.run.xml
  .idea/runConfigurations/DataNucleus Enhance.run.xml
  .idea/runConfigurations/Jetty with PostgreSQL.run.xml
  .idea/runConfigurations/Jetty.run.xml
  .idea/runConfigurations/Test.run.xml
  DEVELOPING.md
  dev/scripts/data-nist-generate-dummy.sh
  dev/scripts/dbschema-generate.datanucleus.properties
  dev/scripts/dbschema-generate.log4j.properties
  dev/scripts/dbschema-generate.sh
  dev/scripts/logs-clear.sh
Labels: enhancement

#374 Version Distance policy evaluator
  src/main/java/org/dependencytrack/exception/PolicyException.java
  src/main/java/org/dependencytrack/model/PolicyCondition.java
  src/main/java/org/dependencytrack/policy/ComponentAgePolicyEvaluator.java
  src/main/java/org/dependencytrack/policy/PolicyEngine.java
  src/main/java/org/dependencytrack/policy/VersionDistancePolicyEvaluator.java
  src/main/java/org/dependencytrack/util/VersionDistance.java
  src/test/java/org/dependencytrack/policy/VersionDistancePolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/util/VersionDistanceTest.java
Labels: enhancement

#366 Add new endpoint for DependencyGraph
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/RepositoryQueryManager.java
  src/main/java/org/dependencytrack/persistence/ServiceComponentQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/DependencyGraphResource.java
  src/main/java/org/dependencytrack/resources/v1/vo/DependencyGraphResponse.java
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/DependencyGraphResourceTest.java
Labels: enhancement

#377 changes for end points with integrity meta
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/ComponentMetaInformation.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/util/ComponentIdentificationUtil.java
  src/test/java/org/dependencytrack/persistence/QueryManagerTest.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
Labels: enhancement

#376 Support pass-through properties for Kafka Streams and Kafka Producer
  src/main/java/org/dependencytrack/event/kafka/KafkaProducerInitializer.java
  src/main/java/org/dependencytrack/event/kafka/KafkaStreamsInitializer.java
Labels: enhancement

#379 Bump Snappy to 1.1.10.5
  pom.xml
Labels: dependencies, java

#381 Vex resource test
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
Labels: enhancement

#382 Fix version distance policy being evaluated despite not being configured
  src/main/java/org/dependencytrack/policy/VersionDistancePolicyEvaluator.java
Labels: bug

#385 Fix AffectedComponent format for CPEs with version ranges
  src/main/java/org/dependencytrack/resources/v1/vo/AffectedComponent.java
  src/test/java/org/dependencytrack/resources/v1/vo/AffectedComponentTest.java
Labels: bug

#383 Include Cloud SQL database connector for PostgreSQL
  pom.xml
Labels: enhancement

#384 Fix invalid Mattermost & Slack notification templates
  src/main/resources/templates/notification/publisher/mattermost.peb
  src/main/resources/templates/notification/publisher/slack.peb
Labels: bug

#387 Port image upgrades from upstream
  .github/dependabot.yml
  pom.xml
  src/main/docker/Dockerfile
Labels: enhancement

#391 Fix integrity meta initializer
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/event/IntegrityMetaInitializer.java
  src/main/java/org/dependencytrack/event/IntegrityMetaInitializerEvent.java
  src/main/java/org/dependencytrack/event/PurlMigrator.java
  src/main/java/org/dependencytrack/event/kafka/processor/RepositoryMetaResultProcessor.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/IntegrityMetaQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/tasks/IntegrityMetaInitializerTask.java
  src/main/java/org/dependencytrack/tasks/LockName.java
  src/main/java/org/dependencytrack/tasks/TaskScheduler.java
  src/main/java/org/dependencytrack/util/LockProvider.java
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/web.xml
  src/test/java/org/dependencytrack/event/IntegrityMetaInitializerTest.java
  src/test/java/org/dependencytrack/event/PurlMigratorTest.java
  src/test/java/org/dependencytrack/persistence/IntegrityMetaQueryManagerPostgresTest.java
  src/test/java/org/dependencytrack/persistence/IntegrityMetaQueryManagerTest.java
  src/test/java/org/dependencytrack/tasks/IntegrityMetaInitializerTaskTest.java
Labels: bug

#393 Implement SPDX expressions
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParser.java
  src/main/java/org/dependencytrack/parser/spdx/expression/model/SpdxExpression.java
  src/main/java/org/dependencytrack/parser/spdx/expression/model/SpdxExpressionOperation.java
  src/main/java/org/dependencytrack/parser/spdx/expression/model/SpdxOperator.java
  src/main/java/org/dependencytrack/parser/spdx/expression/package-info.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/main/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluator.java
  src/main/java/org/dependencytrack/policy/LicensePolicyEvaluator.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyEngine.java
  src/main/java/org/dependencytrack/policy/cel/mapping/ComponentProjection.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/parser/spdx/expression/SpdxExpressionParserTest.java
  src/test/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/LicensePolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyEngineTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: enhancement

#397 Cyclonedx-core-java library version bump
  pom.xml
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-1.xml
  src/test/resources/unit/bom-issue2519.xml
Labels: enhancement, dependencies, java

#403 Fix impossible SQL query conditions causing DB indexes to be bypassed
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
Labels: bug

#409 Integrity analysis if integrity metadata is present
  src/main/java/org/dependencytrack/event/kafka/componentmeta/IntegrityCheck.java
  src/main/java/org/dependencytrack/event/kafka/processor/RepositoryMetaResultProcessor.java
  src/test/java/org/dependencytrack/event/kafka/processor/RepositoryMetaResultProcessorTest.java
Labels: bug
