Repository DependencyTrack/hyades-apiserver, pull requests merged in 2023-04, with the labels that each got.

#80 Record time metrics for event processors
  src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
  src/main/java/org/dependencytrack/event/kafka/processor/RepositoryMetaResultProcessor.java
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
Labels: enhancement

#79 Enable Snappy compression
  src/main/java/org/dependencytrack/event/kafka/KafkaProducerInitializer.java
  src/main/java/org/dependencytrack/event/kafka/KafkaStreamsInitializer.java
Labels: enhancement

#77 Make better use of producer batching when dispatching events to Kafka
  src/main/java/org/dependencytrack/event/kafka/KafkaEvent.java
  src/main/java/org/dependencytrack/event/kafka/KafkaEventConverter.java
  src/main/java/org/dependencytrack/event/kafka/KafkaEventDispatcher.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/NistMirrorTask.java
  src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
  src/main/java/org/dependencytrack/tasks/RepositoryMetaAnalyzerTask.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
  src/main/java/org/dependencytrack/util/NotificationUtil.java
  src/test/java/org/dependencytrack/event/kafka/KafkaEventDispatcherTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: enhancement

#78 Fix NullPointerException when processing mirrored vulnerabilities
  src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
Labels: bug

#74 Rework Mirror service
  src/main/java/org/dependencytrack/event/kafka/KafkaEventDispatcher.java
  src/main/java/org/dependencytrack/event/kafka/KafkaTopics.java
  src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
  src/main/java/org/dependencytrack/resources/v1/OsvEcosytemResource.java
  src/main/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTask.java
  src/main/java/org/dependencytrack/tasks/OsvDownloadTask.java
  src/main/proto/org/cyclonedx/v1_4/cyclonedx.proto
  src/test/java/org/dependencytrack/event/kafka/KafkaEventDispatcherTest.java
  src/test/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessorTest.java
  src/test/java/org/dependencytrack/resources/v1/OsvEcosystemResourceTest.java
  src/test/java/org/dependencytrack/tasks/GitHubAdvisoryMirrorTaskTest.java
  src/test/java/org/dependencytrack/util/KafkaTestUtil.java
Labels: enhancement

#87 Disable alias synchronization when ingesting mirrored vulnerabilities
  src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
Labels: enhancement

#84 Remove Kafka JSON serialization classes
  src/main/java/org/dependencytrack/event/kafka/serialization/JacksonDeserializer.java
  src/main/java/org/dependencytrack/event/kafka/serialization/JacksonSerde.java
  src/main/java/org/dependencytrack/event/kafka/serialization/JacksonSerializer.java
Labels: enhancement

#92 Port fix for faulty ACL query assembly in certain situations from upstream
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: bug

#91 Port fix for ineffective cloning of ACLs from upstream
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
Labels: bug

#90 Port fix for `AlreadyClosedException` on search index commit from upstream
  src/main/java/org/dependencytrack/search/IndexManager.java
  src/main/java/org/dependencytrack/search/IndexSubsystemInitializer.java
Labels: bug

#93 Port support for dependency graph in CycloneDX exports from upstream
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Labels: enhancement

#94 Bump Alpine to 2.2.1
  pom.xml
Labels: dependencies, java

#99 Port fixes for NPEs during policy evaluation
  src/main/java/org/dependencytrack/policy/CoordinatesPolicyEvaluator.java
  src/main/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluator.java
  src/test/java/org/dependencytrack/policy/CoordinatesPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluatorTest.java
Labels: bug

#82 Track vulnerability analysis target
  src/main/java/org/dependencytrack/event/kafka/KafkaStreamsTopologyFactory.java
  src/main/java/org/dependencytrack/model/VulnerabilityScan.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/policy/PolicyEngine.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/event/kafka/KafkaStreamsTopologyTest.java
Labels: enhancement

#95 Port health check implementation from upstream
  pom.xml
  src/main/docker/Dockerfile
  src/main/java/org/dependencytrack/health/DatabaseHealthCheck.java
  src/main/java/org/dependencytrack/health/HealthCheckInitializer.java
  src/main/java/org/dependencytrack/health/HealthCheckResponseBuilder.java
  src/main/java/org/dependencytrack/health/HealthCheckResponseProvider.java
  src/main/java/org/dependencytrack/health/HealthCheckServlet.java
  src/main/java/org/dependencytrack/health/KafkaStreamsHealthCheck.java
  src/main/resources/META-INF/services/org.eclipse.microprofile.health.spi.HealthCheckResponseProvider
  src/main/webapp/WEB-INF/web.xml
Labels: enhancement

#102 Port fix to allow for component author names to exceed 255 characters
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/upgrade/UpgradeItems.java
  src/main/java/org/dependencytrack/upgrade/v480/v480Updater.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/bom-1.xml
Labels: bug

#104 Port fix for dependency graph not being imported properly for nested components
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
Labels: bug

#112 Fix tests not being executed
  pom.xml
Labels: bug

#110 backporting bugfixes for issue 2439 from upstream dependency track
  src/main/java/org/dependencytrack/model/Project.java
Labels: bug

#109 Feature/backportbugfix2338
  src/main/java/org/dependencytrack/integrations/defectdojo/DefectDojoClient.java
  src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java
Labels: enhancement

#113 Track vulnerability scan completion for manually triggered reanalysis
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/event/VulnerabilityScanCleanupEvent.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/TaskScheduler.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityScanCleanupTask.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/java/org/dependencytrack/tasks/VulnerabilityAnalysisTaskTest.java
  src/test/java/org/dependencytrack/tasks/VulnerabilityScanCleanupTaskTest.java
Labels: bug

#125 Allow H2 web console usage for dev purposes
  .run/Jetty with H2 Console.run.xml
  pom.xml
  src/main/java/org/dependencytrack/persistence/H2WebConsoleInitializer.java
  src/main/webapp/WEB-INF/web.xml
  src/test/webapp/WEB-INF/h2-console-activation.xml
Labels: enhancement

#127 Add DefectDojo "do not reactivate" flag
  docs/_docs/integrations/defectdojo.md
  docs/images/screenshots/defectdojo_do-not-reactivate.png
  src/main/java/org/dependencytrack/integrations/defectdojo/DefectDojoClient.java
  src/main/java/org/dependencytrack/integrations/defectdojo/DefectDojoUploader.java
  src/test/java/org/dependencytrack/integrations/defectdojo/DefectDojoClientTest.java
Labels: enhancement

#129 Port fix for correlation of unrelated vulnerability aliases
  src/main/java/org/dependencytrack/model/VulnerabilityAlias.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/test/java/org/dependencytrack/persistence/VulnerabilityQueryManagerTest.java
Labels: bug

#130 Disable DataNucleus L2 cache for mirroring tasks
  src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
Labels: enhancement

#131 Move nist mirror task to eventservice and add developer docs for skipping NVD mirroring
  DEVELOPING.md
  scripts/data-nist-generate-dummy.sh
  src/main/java/org/dependencytrack/event/EpssMirrorEvent.java
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/event/NistMirrorEvent.java
Labels: enhancement

#136 Improve analysis event dispatch throughput
  src/main/java/org/dependencytrack/event/ComponentRepositoryMetaAnalysisEvent.java
  src/main/java/org/dependencytrack/event/ComponentVulnerabilityAnalysisEvent.java
  src/main/java/org/dependencytrack/event/PortfolioRepositoryMetaAnalysisEvent.java
  src/main/java/org/dependencytrack/event/kafka/KafkaEventConverter.java
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/main/java/org/dependencytrack/tasks/RepositoryMetaAnalyzerTask.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
  src/test/java/org/dependencytrack/event/ComponentVulnerabilityAnalysisEventTest.java
Labels: enhancement

#137 Disable DataNucleus L2 cache for metrics update tasks
  src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java
Labels: enhancement

#141 Fix CVSSv2 score being overwritten with CVSSv3 score
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
Labels: bug

#143 Collect timer metrics for metrics updates and policy evaluations
  src/main/java/org/dependencytrack/policy/PolicyEngine.java
  src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/VulnerabilityMetricsUpdateTask.java
Labels: enhancement

#142 Add Kafka client and streams logging config
  src/main/docker/logback.xml
Labels: enhancement
