Repository DependencyTrack/hyades-apiserver, pull requests merged in 2023-07, with the labels that each got.

#212 Fix missing subject in `PROJECT_CREATED` notification
  src/main/java/org/dependencytrack/parser/hyades/NotificationModelConverter.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/util/NotificationUtil.java
  src/test/java/org/dependencytrack/parser/hyades/NotificationModelConverterTest.java
Labels: bug

#222 Lock singleton tasks
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/tasks/EpssMirrorTask.java
  src/main/java/org/dependencytrack/tasks/InternalComponentIdentificationTask.java
  src/main/java/org/dependencytrack/tasks/LdapSyncTaskWrapper.java
  src/main/java/org/dependencytrack/tasks/LockName.java
  src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/VulnerabilityMetricsUpdateTask.java
  src/main/java/org/dependencytrack/util/LockProvider.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/tasks/InternalComponentIdentificationTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/VulnerabilityMetricsUpdateTaskTest.java
  src/test/resources/shedlock_h2.sql
Labels: enhancement

#224 Include reason for rejected BOM upload in API response
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Labels: dependencies

#218 Improve BOM processing performance
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/BomUploadEvent.java
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/ComponentIdentity.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/FlushHelper.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/util/PersistenceUtil.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/event/BomUploadEventTest.java
  src/test/java/org/dependencytrack/model/ComponentIdentityTest.java
  src/test/java/org/dependencytrack/persistence/FlushHelperTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/java/org/dependencytrack/util/KafkaTestUtil.java
  src/test/java/org/dependencytrack/util/PersistenceUtilTest.java
  src/test/resources/bom-1.xml
  src/test/resources/unit/bom-1.xml
  src/test/resources/unit/bom-issue1905.json
  src/test/resources/unit/bom-issue2519.xml
Labels: enhancement

#229 Fix memory leak issue in vex upload processing task
  src/main/java/org/dependencytrack/tasks/VexUploadProcessingTask.java
Labels: bug

#230 Fix memory leak issue in policy evaluation
  src/main/java/org/dependencytrack/policy/AbstractPolicyEvaluator.java
  src/test/java/org/dependencytrack/policy/ComponentHashPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/CoordinatesPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/CpePolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/LicenseGroupPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/LicensePolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/PackageURLPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/SwidTagIdPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/VersionPolicyEvaluatorTest.java
Labels: bug

#239 Implement Kafka Streams exception handlers
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/kafka/KafkaStreamsInitializer.java
  src/main/java/org/dependencytrack/event/kafka/exception/AbstractThresholdBasedExceptionHandler.java
  src/main/java/org/dependencytrack/event/kafka/exception/KafkaStreamsDeserializationExceptionHandler.java
  src/main/java/org/dependencytrack/event/kafka/exception/KafkaStreamsProductionExceptionHandler.java
  src/main/java/org/dependencytrack/event/kafka/exception/KafkaStreamsUncaughtExceptionHandler.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/event/kafka/exception/KafkaStreamsDeserializationExceptionHandlerTest.java
  src/test/java/org/dependencytrack/event/kafka/exception/KafkaStreamsProductionExceptionHandlerTest.java
  src/test/java/org/dependencytrack/event/kafka/exception/KafkaStreamsUncaughtExceptionHandlerTest.java
Labels: enhancement

#243 Add rest endpoint for workflow status
  src/main/java/org/dependencytrack/model/WorkflowState.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/WorkflowResource.java
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/WorkflowResourceTest.java
Labels: enhancement

#247 Bom consumption and processing workflow
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/WorkflowStateQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/AbstractPostgresEnabledTest.java
  src/test/java/org/dependencytrack/persistence/WorkflowQueryManagerTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: enhancement

#242 Update IntelliJ run configurations
  .run/Build API Server Image.run.xml
  .run/Build Bundled Image.run.xml
  .run/Jetty with PostgreSQL.run.xml
Labels: enhancement

#250 Add workflow update for metrics calculation
  src/main/java/org/dependencytrack/event/ComponentMetricsUpdateEvent.java
  src/main/java/org/dependencytrack/event/kafka/KafkaStreamsTopologyFactory.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/WorkflowStateQueryManager.java
  src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTaskTest.java
Labels: enhancement

#253 Add workflow state for policy evaluation
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/WorkflowStateQueryManager.java
  src/main/java/org/dependencytrack/tasks/PolicyEvaluationTask.java
  src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/tasks/PolicyEvaluationTaskTest.java
Labels: enhancement

#254 Create workflow steps on reanalysis
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/WorkflowStateQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
  src/test/java/org/dependencytrack/tasks/TaskSchedulerTest.java
Labels: enhancement

#249 Add cleanup task for workflow states
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/event/WorkflowStateCleanupEvent.java
  src/main/java/org/dependencytrack/model/WorkflowState.java
  src/main/java/org/dependencytrack/persistence/WorkflowStateQueryManager.java
  src/main/java/org/dependencytrack/tasks/LockName.java
  src/main/java/org/dependencytrack/tasks/TaskScheduler.java
  src/main/java/org/dependencytrack/tasks/WorkflowStateCleanupTask.java
  src/main/java/org/dependencytrack/util/LockProvider.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/persistence/WorkflowQueryManagerTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/WorkflowResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/java/org/dependencytrack/tasks/WorkflowStateCleanupTaskTest.java
Labels: enhancement
