Repository DependencyTrack/hyades-apiserver, pull requests merged in 2023-12, with the labels that each got.

#461 Add JDBI integration
  pom.xml
  src/main/java/org/dependencytrack/persistence/jdbi/JdbiFactory.java
  src/main/java/org/dependencytrack/persistence/jdbi/JdoConnectionFactory.java
  src/test/java/org/dependencytrack/persistence/jdbi/JdbiFactoryTest.java
Labels: enhancement

#464 Implement `VulnerabilityPolicyEvaluator` (without dynamic loading of required fields)
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
  src/main/java/org/dependencytrack/policy/cel/CelComponentPolicyLibrary.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyEngine.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyScriptHost.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyType.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyVariable.java
  src/main/java/org/dependencytrack/policy/cel/CelVulnerabilityPolicyEvaluator.java
  src/main/java/org/dependencytrack/policy/cel/CelVulnerabilityPolicyLibrary.java
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicy.java
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicyAnalysis.java
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicyEvaluator.java
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicyProvider.java
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicyRating.java
  src/main/java/org/dependencytrack/resources/v1/PolicyConditionResource.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyScriptHostTest.java
  src/test/java/org/dependencytrack/policy/cel/CelVulnerabilityPolicyEvaluatorTest.java
Labels: enhancement

#470 Implement database-backed `VulnerabilityPolicyProvider`
  src/main/java/org/dependencytrack/model/VulnerabilityPolicy.java
  src/main/java/org/dependencytrack/model/vulnerabilitypolicy/VulnerabilityPolicyAnalysis.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityPolicyQueryManager.java
  src/main/java/org/dependencytrack/policy/cel/CelVulnerabilityPolicyEvaluator.java
  src/main/java/org/dependencytrack/policy/vulnerability/DatabaseVulnerabilityPolicyProvider.java
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicyAnalysis.java
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicyRating.java
  src/main/resources/META-INF/services/org.dependencytrack.policy.vulnerability.VulnerabilityPolicyEvaluator
  src/main/resources/META-INF/services/org.dependencytrack.policy.vulnerability.VulnerabilityPolicyProvider
  src/test/java/org/dependencytrack/persistence/VulnerabilityPolicyQueryManagerTest.java
Labels: enhancement

#476 Reuse testcontainers database across test methods
  src/test/java/org/dependencytrack/AbstractPostgresEnabledTest.java
  src/test/java/org/dependencytrack/persistence/IntegrityMetaQueryManagerPostgresTest.java
Labels: enhancement

#479 Fix Alpine not having been updated to 2.2.4
  pom.xml
Labels: dependencies, java

#481 Use `ResultSet#getTimestamp` over `ResultSet#getDate` when mapping vuln policies
  src/main/java/org/dependencytrack/persistence/VulnerabilityPolicyQueryManager.java
Labels: enhancement

#482 Move vuln policy schema to `resources`
  src/main/resources/schema/vulnerability-policy-v1.schema.json
  src/test/java/org/dependencytrack/policy/validation/PolicySchemaValidationTest.java
  src/test/resources/unit/policy/vulnerability-policy-v1-invalid.yaml
  src/test/resources/unit/policy/vulnerability-policy-v1-valid.yaml
Labels: bug

#472 Extend Analysis model to additionally hold rating overrides
  src/main/java/org/dependencytrack/model/Analysis.java
  src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/resources/migration/changelog-v5.3.0.xml
  src/main/resources/migration/procedures/function_calc-severity.sql
  src/main/resources/migration/procedures/procedure_update-component-metrics.sql
  src/test/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTaskTest.java
Labels: enhancement

#484 Improve performance of `is_dependency_of` query
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
Labels: enhancement

#465 Dynamic loading of fields for policy evaluation
  pom.xml
  src/main/java/org/dependencytrack/persistence/jdbi/JdbiFactory.java
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyEngine.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyScriptHost.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyVariable.java
  src/main/java/org/dependencytrack/policy/cel/CelVulnerabilityPolicyEvaluator.java
  src/main/java/org/dependencytrack/policy/cel/definition/CelPolicyTypes.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyComponentRowMapper.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyDao.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyProjectRowMapper.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyRowMapperUtil.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyVulnerabilityRowMapper.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyEngineTest.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyScriptHostTest.java
  src/test/java/org/dependencytrack/policy/cel/CelVulnerabilityPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/policy/cel/persistence/CelPolicyDaoTest.java
Labels: enhancement

#485 Fix `is_dependency_of` query template
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyEngineTest.java
Labels: bug

#486 Cleanup vuln policy bundle properties
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/tasks/TaskScheduler.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/AbstractVulnerabilityPolicyFetcher.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/BlobStorageAccessFactory.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/BlobStorageHandlerFactoryTest.java
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/NginxPolicyFetcherTest.java
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/VulnerabilityPolicyFetchTaskTest.java
Labels: enhancement

#474 Integrate vulnerability policy evaluation into scan result processing
  src/main/java/org/dependencytrack/event/kafka/KafkaEventConverter.java
  src/main/java/org/dependencytrack/event/kafka/KafkaEventDispatcher.java
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/model/mapping/PolicyProtoMapper.java
  src/main/java/org/dependencytrack/util/PersistenceUtil.java
  src/main/resources/migration/changelog-v5.3.0.xml
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/model/mapping/PolicyProtoMapperTest.java
  src/test/java/org/dependencytrack/util/PersistenceUtilTest.java
Labels: enhancement

#491 Record matched vuln policy conditions in audit trail
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
Labels: enhancement

#492 Fix vuln policy ratings getting persisted as `"null"` string when `null`
  src/main/java/org/dependencytrack/persistence/VulnerabilityPolicyQueryManager.java
Labels: bug

#488 Consider rating overrides for `NEW_VULNERABILITY` and `NEW_VULNERABLE_DEPENDENCY` notifications
  src/main/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/NotificationComponentRowMapper.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/NotificationProjectRowMapper.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/NotificationSubjectNewVulnerabilityRowMapper.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/NotificationVulnerabilityRowMapper.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/RowMapperUtil.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyComponentRowMapper.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyDao.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyProjectRowMapper.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyRowMapperUtil.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyVulnerabilityRowMapper.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDaoTest.java
Labels: bug

#487 Add s3 bundle fetch policy support
  pom.xml
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/AbstractVulnerabilityPolicyFetcher.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/BlobStorageAccessFactory.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/BlobStorageAccessHandler.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/GenericStorageHandler.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/NginxStorageHandler.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/S3Client.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/VulnerabilityPolicyFetchTask.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/blobstorage/BlobStorageAccessFactory.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/blobstorage/BlobStorageAccessHandler.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/blobstorage/NginxStorageHandler.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/blobstorage/S3StorageHandler.java
  src/main/java/org/dependencytrack/util/VulnerabilityPolicyUtil.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/S3ClientTest.java
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/VulnerabilityPolicyFetchTaskTest.java
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/blobstorage/BlobStorageHandlerFactoryTest.java
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/blobstorage/MinioContainer.java
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/blobstorage/NginxPolicyFetcherTest.java
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/blobstorage/S3StorageHandlerTest.java
  src/test/java/org/dependencytrack/util/VulnerabilityPolicyUtilTest.java
Labels: enhancement

#490 Add REST endpoint for vulnerability policies
  pom.xml
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityPolicyQueryManager.java
  src/main/java/org/dependencytrack/policy/vulnerability/DatabaseVulnerabilityPolicyProvider.java
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicy.java
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicyProvider.java
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicyProviderFactory.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResource.java
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/persistence/VulnerabilityPolicyQueryManagerTest.java
  src/test/java/org/dependencytrack/resources/v1/AbstractPostgresResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourcePostgresTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResourceTest.java
Labels: enhancement

#493 Fix regression in `NEW_VULNERABILITY` and `NEW_VULNERABLE_DEPENDENCY` title & content
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/NotificationSubjectNewVulnerabilityRowMapper.java
  src/main/java/org/dependencytrack/util/NotificationUtil.java
  src/test/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDaoTest.java
Labels: bug

#497 Set CEL policy container name to `org.dependencytrack.policy`
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
  src/test/java/org/dependencytrack/persistence/VulnerabilityPolicyQueryManagerTest.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyEngineTest.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyScriptHostTest.java
  src/test/resources/unit/policy/vulnerability-policy-v1-invalid.yaml
  src/test/resources/unit/policy/vulnerability-policy-v1-valid.yaml
Labels: enhancement

#498 Tweak vuln policy validation during bundle processing
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/VulnerabilityPolicyFetchTask.java
  src/main/java/org/dependencytrack/util/VulnerabilityPolicyUtil.java
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/VulnerabilityPolicyFetchTaskTest.java
Labels: bug

#500 Fix missing log message arguments
  src/main/java/org/dependencytrack/policy/cel/CelVulnerabilityPolicyEvaluator.java
Labels: bug

#503 Fix various minor bugs in vulnerability policy evaluation
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyScriptHost.java
  src/main/java/org/dependencytrack/policy/cel/CelVulnerabilityPolicyEvaluator.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyDao.java
  src/test/java/org/dependencytrack/TestCacheManager.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyScriptHostTest.java
  src/test/java/org/dependencytrack/policy/cel/CelVulnerabilityPolicyEvaluatorTest.java
Labels: bug

#504 Use lock for `VulnerabilityPolicyFetchTask`
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/tasks/LockName.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/VulnerabilityPolicyFetchTask.java
  src/main/java/org/dependencytrack/util/LockProvider.java
Labels: bug
