Repository DependencyTrack/hyades-apiserver, pull requests merged in 2024-10, with the labels that each got.

#925 Ensure modifying project endpoints are transactional
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: technical debt

#935 Port : Visible Endpoint returns only Visible Teams(name, uuid)
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/main/java/org/dependencytrack/resources/v1/vo/VisibleTeams.java
  src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
Labels: enhancement, v4-port

#944 Fix component `EXTERNAL_REFERENCES` column mapping
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/ExternalReferenceMapper.java
  src/test/java/org/dependencytrack/persistence/VulnerabilityQueryManagerTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: defect

#941 Port : Enhance badge API to require authorization
  src/main/java/org/dependencytrack/auth/Permissions.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/main/java/org/dependencytrack/resources/v1/BadgeResource.java
  src/main/resources/openapi-configuration.yaml
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/auth/PermissionsTest.java
  src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java
  src/test/java/org/dependencytrack/resources/v1/BadgeResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
Labels: enhancement, v4-port

#948 Port : Enhance "Create Project" dialog to include team selection
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/util/PersistenceUtil.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
Labels: enhancement, v4-port

#950 Port : Support configuration of system-wide default locale
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
Labels: enhancement, v4-port
