Repository DependencyTrack/hyades-apiserver, pull requests merged in 2024-12, with the labels that each got.

#987 Fix PURL mismatch of `INTEGRITY_META_COMPONENT` records
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
Labels: defect

#985 defect dojo verified status is now setup from configuration
  src/main/java/org/dependencytrack/integrations/defectdojo/DefectDojoClient.java
  src/main/java/org/dependencytrack/integrations/defectdojo/DefectDojoUploader.java
Labels: enhancement, v4-port

#993 Port: Fix logs not containing usernames of deleted users
  src/main/java/org/dependencytrack/resources/v1/UserResource.java
  src/test/java/org/dependencytrack/resources/v1/UserResourceAuthenticatedTest.java
Labels: defect, v4-port

#994 Fix unintended manual flushing mode due to DataNucleus `ExecutionContext` pooling
  src/main/resources/application.properties
Labels: defect, v4-port

#998 Port: Bump Alpine to 3.1.1
  pom.xml
Labels: dependencies, v4-port

#999 Port: Bump Temurin base image to 21.0.5_11
  src/main/docker/Dockerfile
Labels: dependencies, v4-port

#1005 Fix missing index on `COMPONENT_PROPERTY.COMPONENT_ID`
  src/main/resources/migration/changelog-v5.6.0.xml
Labels: defect

#1006 Reduce database round-trips during BOM processing
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/ComponentIdentity.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/ServiceComponentQueryManager.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
Labels: enhancement

#997 Port: Bump cyclonedx-core-java to 9.1.0
  pom.xml
Labels: dependencies, v4-port
