Repository DependencyTrack/hyades-apiserver, pull requests merged in 2024-06, with the labels that each got.

#690 Add workflow for project cloning
  src/main/java/org/dependencytrack/model/WorkflowStep.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/tasks/CloneProjectTask.java
  src/main/resources/migration/changelog-v5.5.0.xml
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/tasks/CloneProjectTaskTest.java
Labels: enhancement

#697 Backport fix for update component external references
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
Labels: defect, v4-port

#696 Include CVSS and OWASP RR vectors in notifications
  src/main/java/org/dependencytrack/parser/dependencytrack/NotificationModelConverter.java
  src/main/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/NotificationVulnerabilityRowMapper.java
  src/main/proto/org/dependencytrack/notification/v1/notification.proto
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDaoTest.java
Labels: enhancement

#669 Support multiple modes of operation for vulnerability policies
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/model/VulnerabilityPolicy.java
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityPolicyDao.java
  src/main/java/org/dependencytrack/policy/vulnerability/DatabaseVulnerabilityPolicyProvider.java
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicy.java
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicyOperation.java
  src/main/resources/migration/changelog-v5.5.0.xml
  src/main/resources/schema/vulnerability-policy-v1.schema.json
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/VulnerabilityPolicyDaoTest.java
  src/test/java/org/dependencytrack/policy/validation/PolicySchemaValidationTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResourceTest.java
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/VulnerabilityPolicyFetchTaskTest.java
  src/test/java/org/dependencytrack/util/VulnerabilityPolicyUtilTest.java
  src/test/resources/unit/policy/vulnerability-policy-v1-valid.yaml
  src/test/resources/unit/tasks/vulnerabilitypolicy/sample 2.yaml
  src/test/resources/unit/tasks/vulnerabilitypolicy/sample.yaml
  src/test/resources/unit/tasks/vulnerabilitypolicy/sampleInvalid.yaml
Labels: enhancement

#701 Port: enhance API to support frontend changes for active/inactive affected projects
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/java/org/dependencytrack/resources/v1/vo/AffectedProject.java
Labels: enhancement, v4-port

#700 Port mapping for attributed on while cloning project
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/test/java/org/dependencytrack/persistence/ProjectQueryManagerTest.java
Labels: defect, v4-port

#699 Fix CVSS and OWASP RR vectors missing from `PROJECT_VULN_ANALYSIS_COMPLETE` notifications
  src/main/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDao.java
Labels: defect

#702 Add endpoint for updating API key comment
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
Labels: enhancement, v4-port

#703 Port fix jira and slack notification
  src/main/resources/templates/notification/publisher/jira.peb
  src/main/resources/templates/notification/publisher/slack.peb
Labels: defect, v4-port

#705 Port: Refactor BOM upload processing for better efficiency, correctness, and consistency
  src/main/java/org/dependencytrack/common/MdcKeys.java
  src/main/java/org/dependencytrack/event/IntegrityAnalysisEvent.java
  src/main/java/org/dependencytrack/model/License.java
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/InternalComponentIdentificationTask.java
  src/main/java/org/dependencytrack/util/InternalComponentIdentificationUtil.java
  src/main/java/org/dependencytrack/util/InternalComponentIdentifier.java
  src/main/java/org/dependencytrack/util/LockProvider.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/java/org/dependencytrack/tasks/IntegrityAnalysisTaskTest.java
  src/test/java/org/dependencytrack/util/InternalComponentIdentifierTest.java
Labels: enhancement, v4-port

#709 Port: Apply consistent formatting to SQL query
  src/main/java/org/dependencytrack/integrations/kenna/KennaDataTransformer.java
  src/main/java/org/dependencytrack/model/Finding.java
  src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java
  src/test/java/org/dependencytrack/model/FindingTest.java
Labels: defect, v4-port

#711 Add timeout for Kafka API describeTopics commands
  src/main/java/org/dependencytrack/event/kafka/processor/api/ProcessorManager.java
  src/test/java/org/dependencytrack/event/kafka/processor/api/ProcessorManagerTest.java
Labels: defect

#713 Port: Bump CWE dictionary to v4.13
  src/main/java/org/dependencytrack/parser/common/resolver/CweDictionary.java
  src/test/java/org/dependencytrack/resources/v1/CweResourceTest.java
Labels: enhancement, v4-port

#717 Port: Perform License Resolution On Name Field During SBOM Import
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect, v4-port

#716 Port: Fix type of `purl` fields in Swagger docs
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/Project.java
Labels: defect, v4-port

#710 Port: Fix subject mappings for project in `NewVulnerableDependencySubject`
  src/main/resources/templates/notification/publisher/email.peb
  src/main/resources/templates/notification/publisher/jira.peb
  src/main/resources/templates/notification/publisher/msteams.peb
  src/main/resources/templates/notification/publisher/slack.peb
Labels: defect, v4-port

#721 Port: Add `ConstraintViolationExceptionMapper` to support `@ValidUuid`
  src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
  src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/BadgeResource.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/DependencyGraphResource.java
  src/main/java/org/dependencytrack/resources/v1/EventResource.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/main/java/org/dependencytrack/resources/v1/LdapResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseGroupResource.java
  src/main/java/org/dependencytrack/resources/v1/MetricsResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
  src/main/java/org/dependencytrack/resources/v1/OidcResource.java
  src/main/java/org/dependencytrack/resources/v1/PermissionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyConditionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyViolationResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/RepositoryResource.java
  src/main/java/org/dependencytrack/resources/v1/ServiceResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/resources/v1/ViolationAnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/java/org/dependencytrack/resources/v1/exception/ConstraintViolationExceptionMapper.java
  src/test/java/org/dependencytrack/resources/v1/exception/ConstraintViolationExceptionMapperTest.java
Labels: enhancement, v4-port

#720 Port: Include pagination parameters in OpenAPI spec
  src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/CweResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseGroupResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyViolationResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/RepositoryResource.java
  src/main/java/org/dependencytrack/resources/v1/ServiceResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/java/org/dependencytrack/resources/v1/WorkflowResource.java
  src/main/java/org/dependencytrack/resources/v1/openapi/PaginatedApi.java
Labels: enhancement, v4-port

#706 Port: Store computed severities in the database
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/parser/dependencytrack/ModelConverterCdxToVuln.java
  src/main/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDao.java
  src/main/java/org/dependencytrack/persistence/migration/change/v550/ComputeSeveritiesChange.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/resources/migration/changelog-procedures.xml
  src/main/resources/migration/changelog-v5.5.0.xml
  src/main/resources/migration/procedures/function_calc-severity.sql
  src/main/resources/migration/procedures/function_cvssv2-to-severity.sql
  src/main/resources/migration/procedures/function_cvssv3-to-severity.sql
  src/main/resources/migration/procedures/procedure_update-component-metrics.sql
  src/test/java/org/dependencytrack/model/VulnerabilityTest.java
  src/test/java/org/dependencytrack/model/mapping/PolicyProtoMapperTest.java
  src/test/java/org/dependencytrack/parser/dependencytrack/NotificationModelConverterTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDaoTest.java
  src/test/java/org/dependencytrack/persistence/migration/change/v550/ComputeSeveritiesChangeTest.java
  src/test/resources/migration/custom/ComputeSeveritiesChangeTest-changelog.xml
  src/test/resources/migration/custom/ComputeSeveritiesChangeTest-schema.sql
Labels: enhancement, v4-port

#726 Port: Disable Maven transfer progress in CI
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-release.yaml
  .github/workflows/ci-test.yaml
Labels: dx, v4-port

#725 Port: Disable automatic API key generation for teams
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
Labels: enhancement, v4-port

#727 Port: Reduce verbosity of `ResourceTest`s
  pom.xml
  src/test/resources/logging.properties
Labels: dx, v4-port

#718 Customize risk score calculation
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/resources/v1/AbstractConfigPropertyResource.java
  src/main/resources/migration/procedures/function_calc-risk-score.sql
  src/test/java/org/dependencytrack/event/kafka/processor/ProcessedVulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/metrics/MetricsTest.java
  src/test/java/org/dependencytrack/resources/v1/ConfigPropertyResourceTest.java
  src/test/java/org/dependencytrack/tasks/metrics/AbstractMetricsUpdateTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTaskTest.java
Labels: enhancement

#723 Port: Global Audit View for vulnerabilities
  src/main/java/org/dependencytrack/model/Finding.java
  src/main/java/org/dependencytrack/model/GroupedFinding.java
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/test/java/org/dependencytrack/model/GroupedFindingTest.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: enhancement, v4-port

#729 Port: add hackage and nixpkgs analyzers
  src/main/java/org/dependencytrack/model/RepositoryType.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/test/java/org/dependencytrack/model/RepositoryTypeTest.java
  src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java
  src/test/java/org/dependencytrack/resources/v1/RepositoryResourceTest.java
Labels: enhancement, v4-port

#731 Bump various dependencies
  pom.xml
Labels: dependencies, java

#736 Remove dependency on `kafka-junit`
  pom.xml
  src/test/java/org/dependencytrack/event/kafka/processor/api/ProcessorManagerTest.java
Labels: technical debt

#715 Port: Validate uploaded BOMs against CycloneDX schema
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/main/java/org/dependencytrack/parser/cyclonedx/InvalidBomException.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/resources/v1/problems/InvalidBomProblemDetails.java
  src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
Labels: enhancement, v4-port

#742 Port: Webhook alert token and new user alerts
  src/main/java/org/dependencytrack/event/kafka/KafkaEventConverter.java
  src/main/java/org/dependencytrack/event/kafka/KafkaTopics.java
  src/main/java/org/dependencytrack/notification/NotificationConstants.java
  src/main/java/org/dependencytrack/notification/NotificationGroup.java
  src/main/java/org/dependencytrack/parser/dependencytrack/NotificationModelConverter.java
  src/main/java/org/dependencytrack/resources/v1/UserResource.java
  src/main/proto/org/dependencytrack/notification/v1/notification.proto
  src/test/java/org/dependencytrack/notification/NotificationConstantsTest.java
  src/test/java/org/dependencytrack/notification/NotificationGroupTest.java
  src/test/java/org/dependencytrack/resources/v1/UserResourceAuthenticatedTest.java
Labels: enhancement, v4-port

#722 Port: OpenAPI spec fixes and improvements
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
  src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/ConfigPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/DependencyGraphResource.java
  src/main/java/org/dependencytrack/resources/v1/EventResource.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/main/java/org/dependencytrack/resources/v1/IntegrationResource.java
  src/main/java/org/dependencytrack/resources/v1/LdapResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseGroupResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseResource.java
  src/main/java/org/dependencytrack/resources/v1/MetricsResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
  src/main/java/org/dependencytrack/resources/v1/OidcResource.java
  src/main/java/org/dependencytrack/resources/v1/PermissionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyConditionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyViolationResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/RepositoryResource.java
  src/main/java/org/dependencytrack/resources/v1/ServiceResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/main/java/org/dependencytrack/resources/v1/UserResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/resources/v1/ViolationAnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityPolicyBundleResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/java/org/dependencytrack/resources/v1/WorkflowResource.java
  src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
  src/main/java/org/dependencytrack/resources/v1/vo/BomSubmitRequest.java
  src/test/java/org/dependencytrack/resources/v1/IntegrationResourceTest.java
Labels: enhancement, v4-port

#724 Port: Provide meaningful error message for `bom` and `vex` exceeding Jackson's character limit
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/resources/v1/exception/JsonMappingExceptionMapper.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
Labels: defect, v4-port

#745 Port: Add the project name and project URL to bom processing notifications
  src/main/resources/templates/notification/publisher/msteams.peb
Labels: enhancement, v4-port

#743 Port: Include sorting query parameters in OpenAPI spec
  src/main/java/org/dependencytrack/resources/v1/openapi/PaginatedApi.java
Labels: enhancement, v4-port

#746 Port : Generate SARIF File Of Project Vulnerability Findings
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/main/resources/templates/findings/sarif.peb
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: enhancement, v4-port

#747 Port : Fix JDOFatalUserException for long reference URLs from OSS Index
  src/main/java/org/dependencytrack/model/FindingAttribution.java
  src/test/java/org/dependencytrack/model/FindingAttributionTest.java
Labels: defect, v4-port

#744 Port: Catch all unhandled `ClientErrorException`s
  src/main/java/org/dependencytrack/resources/v1/exception/ClientErrorExceptionMapper.java
  src/test/java/org/dependencytrack/resources/v1/exception/ClientErrorExceptionMapperTest.java
Labels: defect, v4-port

#750 Port : Log debug information upon possible secret key corruption
  src/main/java/org/dependencytrack/integrations/fortifyssc/FortifySscUploader.java
  src/main/java/org/dependencytrack/integrations/kenna/KennaSecurityUploader.java
  src/main/java/org/dependencytrack/util/DebugDataEncryption.java
  src/test/java/org/dependencytrack/util/DebugDataEncryptionTest.java
Labels: defect, v4-port

#728 Link to docs for DB migration and doc update checkboxes
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#751 Fix missing argument list for `DROP FUNCTION` migrations
  src/main/resources/migration/changelog-v5.5.0.xml
Labels: defect

#719 Improve efficiency of `InternalComponentIdentificationTask`
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/tasks/InternalComponentIdentificationTask.java
  src/main/java/org/dependencytrack/util/InternalComponentIdentifier.java
Labels: enhancement

#734 Improve Liquibase logging integration
  src/main/java/org/dependencytrack/persistence/migration/LiquibaseLogger.java
  src/main/java/org/dependencytrack/persistence/migration/MigrationInitializer.java
  src/test/java/org/dependencytrack/PostgresTestContainer.java
  src/test/java/org/dependencytrack/persistence/migration/change/v530/RenameForeignKeysChangeTest.java
  src/test/java/org/dependencytrack/persistence/migration/change/v530/RenameNumberedIndexesChangeTest.java
  src/test/java/org/dependencytrack/persistence/migration/change/v550/ComputeSeveritiesChangeTest.java
Labels: enhancement

#748 Port : Truncate component property value
  src/main/java/org/dependencytrack/model/ComponentProperty.java
  src/main/java/org/dependencytrack/model/ProjectProperty.java
  src/main/resources/migration/changelog-v5.5.0.xml
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-1.xml
Labels: enhancement, v4-port

#761 Make `PROJECT.ACTIVE` non-nullable
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/tasks/RepositoryMetaAnalyzerTask.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
  src/main/resources/migration/changelog-v5.5.0.xml
  src/test/java/org/dependencytrack/model/ProjectTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/tasks/RepositoryMetaAnalyzerTaskTest.java
  src/test/java/org/dependencytrack/tasks/VulnerabilityAnalysisTaskTest.java
Labels: enhancement

#754 Port: Support ingestion of CycloneDX v1.6 BOMs
  pom.xml
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/VexUploadProcessingTask.java
  src/main/java/org/dependencytrack/util/VulnerabilityPolicyUtil.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDXVexImporterTest.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
  src/test/java/org/dependencytrack/policy/validation/PolicySchemaValidationTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-schema1.0.xml
  src/test/resources/unit/bom-schema1.1.xml
  src/test/resources/unit/bom-schema1.2.json
  src/test/resources/unit/bom-schema1.2.xml
  src/test/resources/unit/bom-schema1.3.json
  src/test/resources/unit/bom-schema1.3.xml
  src/test/resources/unit/bom-schema1.4.json
  src/test/resources/unit/bom-schema1.4.xml
  src/test/resources/unit/bom-schema1.5.json
  src/test/resources/unit/bom-schema1.5.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.0.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.1.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.2.json
  src/test/resources/unit/cyclonedx/valid-bom-1.2.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.3.json
  src/test/resources/unit/cyclonedx/valid-bom-1.3.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.4.json
  src/test/resources/unit/cyclonedx/valid-bom-1.4.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.5.json
  src/test/resources/unit/cyclonedx/valid-bom-1.5.xml
  src/test/resources/unit/cyclonedx/valid-bom-1.6.json
  src/test/resources/unit/cyclonedx/valid-bom-1.6.xml
Labels: enhancement, v4-port

#692 Improve JDBI integration with Alpine
  src/main/java/org/dependencytrack/event/kafka/processor/ProcessedVulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/metrics/Metrics.java
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/StoredProcedures.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/persistence/jdbi/AllowApiOrdering.java
  src/main/java/org/dependencytrack/persistence/jdbi/ApiRequestConfig.java
  src/main/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizer.java
  src/main/java/org/dependencytrack/persistence/jdbi/JdbiAttributes.java
  src/main/java/org/dependencytrack/persistence/jdbi/JdbiFactory.java
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityPolicyDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/binding/DefineOrdering.java
  src/main/java/org/dependencytrack/persistence/jdbi/binding/DefinePagination.java
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyEngine.java
  src/main/java/org/dependencytrack/policy/cel/CelVulnerabilityPolicyEvaluator.java
  src/main/java/org/dependencytrack/policy/vulnerability/DatabaseVulnerabilityPolicyProvider.java
  src/main/java/org/dependencytrack/tasks/InternalComponentIdentificationTask.java
  src/main/java/org/dependencytrack/util/PrincipalUtil.java
  src/main/java/org/dependencytrack/util/VulnerabilityPolicyUtil.java
  src/test/java/org/dependencytrack/event/kafka/processor/ProcessedVulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizerTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/JdbiFactoryTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDaoTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/VulnerabilityPolicyDaoTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/binding/DefineOrderingTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/binding/DefinePaginationTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/mapping/PaginatedResultRowReducerTest.java
  src/test/java/org/dependencytrack/policy/cel/persistence/CelPolicyDaoTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResourceTest.java
  src/test/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTaskTest.java
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/VulnerabilityPolicyFetchTaskTest.java
  src/test/java/org/dependencytrack/util/VulnerabilityPolicyUtilTest.java
Labels: enhancement

#762 Fix breaking change in vulnerability policy schema
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicy.java
  src/main/resources/migration/changelog-v5.5.0.xml
  src/main/resources/schema/vulnerability-policy-v1.schema.json
  src/test/java/org/dependencytrack/policy/validation/PolicySchemaValidationTest.java
  src/test/java/org/dependencytrack/util/VulnerabilityPolicyUtilTest.java
Labels: defect

#765 Fix NPE when querying component metadata for projects without findings
  src/main/java/org/dependencytrack/persistence/RepositoryQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: defect, v4-port
