Repository DependencyTrack/hyades-apiserver, pull requests merged in 2024-08, with the labels that each got.

#819 Port : Add REST endpoints for tag retrieval
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/vo/TagListResponseItem.java
  src/main/java/org/dependencytrack/resources/v1/vo/TaggedPolicyListResponseItem.java
  src/main/java/org/dependencytrack/resources/v1/vo/TaggedProjectListResponseItem.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: enhancement, v4-port

#820 Port: Improve OpenAPI v3 integration
  pom.xml
  src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
  src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/BadgeResource.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/CalculatorResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/ConfigPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/CweResource.java
  src/main/java/org/dependencytrack/resources/v1/DependencyGraphResource.java
  src/main/java/org/dependencytrack/resources/v1/EventResource.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/main/java/org/dependencytrack/resources/v1/IntegrationResource.java
  src/main/java/org/dependencytrack/resources/v1/LdapResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseGroupResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseResource.java
  src/main/java/org/dependencytrack/resources/v1/MetricsResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
  src/main/java/org/dependencytrack/resources/v1/OidcResource.java
  src/main/java/org/dependencytrack/resources/v1/PermissionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyConditionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyViolationResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/RepositoryResource.java
  src/main/java/org/dependencytrack/resources/v1/ServiceResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/main/java/org/dependencytrack/resources/v1/UserResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/resources/v1/ViolationAnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityPolicyBundleResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/java/org/dependencytrack/resources/v1/WorkflowResource.java
  src/main/resources/openapi-configuration.yaml
  src/main/webapp/WEB-INF/openapi-configuration.yaml
  src/test/java/org/dependencytrack/resources/OpenApiResourceTest.java
Labels: enhancement, v4-port

#822 Update various dependencies
  pom.xml
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/event/kafka/processor/api/ProcessorManagerTest.java
Labels: dependencies, docker, java

#821 Port : Add REST endpoints for bulk tagging & un-tagging of projects
  src/main/java/org/dependencytrack/model/validation/ValidUuid.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: enhancement, v4-port

#824 Port : Add REST endpoint for tag deletion
  src/main/java/org/dependencytrack/auth/Permissions.java
  src/main/java/org/dependencytrack/exception/TagOperationFailedException.java
  src/main/java/org/dependencytrack/model/Policy.java
  src/main/java/org/dependencytrack/model/Tag.java
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
  src/main/java/org/dependencytrack/resources/v1/problems/TagOperationProblemDetails.java
  src/main/java/org/dependencytrack/util/PersistenceUtil.java
  src/test/java/org/dependencytrack/auth/PermissionsTest.java
  src/test/java/org/dependencytrack/persistence/PolicyQueryManagerTest.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyEngineTest.java
  src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: enhancement, v4-port

#830 Port : Add REST endpoints to tag and untag policies in bulk
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: enhancement, v4-port

#834 Port: Add EPSS conditions to policies
  src/main/java/org/dependencytrack/model/PolicyCondition.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyEngine.java
  src/main/java/org/dependencytrack/policy/cel/compat/EpssCelPolicyScriptSourceBuilder.java
  src/test/java/org/dependencytrack/policy/cel/compat/EpssConditionTest.java
Labels: enhancement, v4-port

#833 Port: Fix OpenAPI types of UNIX timestamp fields
  src/main/java/org/dependencytrack/model/AffectedVersionAttribution.java
  src/main/java/org/dependencytrack/model/AnalysisComment.java
  src/main/java/org/dependencytrack/model/Bom.java
  src/main/java/org/dependencytrack/model/DependencyMetrics.java
  src/main/java/org/dependencytrack/model/FindingAttribution.java
  src/main/java/org/dependencytrack/model/IntegrityMetaComponent.java
  src/main/java/org/dependencytrack/model/PolicyViolation.java
  src/main/java/org/dependencytrack/model/PortfolioMetrics.java
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/model/ProjectMetrics.java
  src/main/java/org/dependencytrack/model/RepositoryMetaComponent.java
  src/main/java/org/dependencytrack/model/Vex.java
  src/main/java/org/dependencytrack/model/ViolationAnalysisComment.java
  src/main/java/org/dependencytrack/model/VulnerabilityMetrics.java
  src/main/java/org/dependencytrack/resources/v1/vo/IsTokenBeingProcessedResponse.java
Labels: defect, v4-port

#832 Port: Gracefully handle `NotSortableException`s
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/exception/NotSortableExceptionMapper.java
  src/test/java/org/dependencytrack/resources/v1/exception/NotSortableExceptionMapperTest.java
Labels: enhancement, v4-port

#837 Bump Redpanda to v24.2.2
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/event/kafka/processor/api/ProcessorManagerTest.java
Labels: dependencies, docker

#836 Port : Search component by group
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourcePostgresTest.java
Labels: enhancement, v4-port

#835 Port : Fix project link for new vulnerable dependency for email
  src/main/resources/templates/notification/publisher/email.peb
Labels: defect, v4-port

#841 Reduce `MaxRAMPercentage` from 90% to 80%
  src/main/docker/Dockerfile
Labels: enhancement

#842 Port: Bump CWE dictionary to v4.14
  src/main/java/org/dependencytrack/parser/common/resolver/CweDictionary.java
  src/test/java/org/dependencytrack/resources/v1/CweResourceTest.java
Labels: enhancement, v4-port

#845 Port: Set license name instead of ID when using custom license
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Labels: defect, v4-port

#851 Fix ordering of concise projects not allowed for `active` and `metrics.policyViolationsTotal`
  src/main/java/org/dependencytrack/persistence/jdbi/ProjectDao.java
Labels: defect

#852 Port : Fix vex export returning invalid CycloneDX
  pom.xml
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
  src/test/java/org/dependencytrack/policy/validation/PolicySchemaValidationTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
Labels: defect, v4-port

#854 Bump Alpine to 3.0.1
  pom.xml
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
Labels: dependencies, java

#859 Change `dbschema-generate.sh` to dump the final schema instead of the entire changelog
  dev/scripts/dbschema-generate.sh
Labels: dx

#869 Fix Liquibase blocking when running out of entropy
  pom.xml
Labels: defect

#870 Revert "Revert "Use native `UUID` type for UUID colums""
  src/main/java/org/dependencytrack/event/kafka/processor/ProcessedVulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/metrics/Metrics.java
  src/main/java/org/dependencytrack/model/AffectedVersionAttribution.java
  src/main/java/org/dependencytrack/model/Bom.java
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/ComponentProperty.java
  src/main/java/org/dependencytrack/model/FindingAttribution.java
  src/main/java/org/dependencytrack/model/License.java
  src/main/java/org/dependencytrack/model/LicenseGroup.java
  src/main/java/org/dependencytrack/model/NotificationPublisher.java
  src/main/java/org/dependencytrack/model/NotificationRule.java
  src/main/java/org/dependencytrack/model/Policy.java
  src/main/java/org/dependencytrack/model/PolicyCondition.java
  src/main/java/org/dependencytrack/model/PolicyViolation.java
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/model/Repository.java
  src/main/java/org/dependencytrack/model/ServiceComponent.java
  src/main/java/org/dependencytrack/model/Vex.java
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/model/VulnerabilityAlias.java
  src/main/java/org/dependencytrack/model/VulnerabilityScan.java
  src/main/java/org/dependencytrack/model/VulnerableSoftware.java
  src/main/java/org/dependencytrack/model/WorkflowState.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/main/java/org/dependencytrack/persistence/WorkflowStateQueryManager.java
  src/main/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/ProjectDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityScanDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/WorkflowDao.java
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyQueryManager.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyDao.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
  src/main/resources/migration/changelog-main.xml
  src/main/resources/migration/changelog-v5.6.0.xml
  src/main/resources/migration/procedures/procedure_update-component-metrics.sql
  src/main/resources/migration/procedures/procedure_update-project-metrics.sql
  src/test/java/org/dependencytrack/event/kafka/processor/ProcessedVulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/java/org/dependencytrack/tasks/TaskSchedulerTest.java
  src/test/java/org/dependencytrack/tasks/VulnerabilityAnalysisTaskTest.java
  src/test/java/org/dependencytrack/tasks/VulnerabilityScanCleanupTaskTest.java
Labels: enhancement

#873 Add `init.and.exit` and `init.tasks.enabled` options
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/main/java/org/dependencytrack/persistence/migration/MigrationInitializer.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java
  src/test/java/org/dependencytrack/persistence/migration/MigrationInitializerTest.java
Labels: enhancement

#874 Port: Fix validation error when multiple namespace declarations are present
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/resources/unit/bom-issue4008.xml
Labels: defect, v4-port

#877 Prevent concurrent execution of `DefaultObjectGenerator`
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
Labels: enhancement

#876 Ensure process exiting upon migration failure when `init.and.exit` is set
  src/main/java/org/dependencytrack/persistence/migration/MigrationInitializer.java
Labels: defect

#875 Specify `metadata-complete="true"` in `web.xml`
  src/main/webapp/WEB-INF/web.xml
Labels: enhancement

#878 Avoid redundant defaultobject generation
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java
Labels: enhancement
