Repository DependencyTrack/hyades-apiserver, pull requests merged in 2024-09, with the labels that each got.

#882 Port: Bump DataNucleus to 6.0.8
  pom.xml
Labels: dependencies, java, v4-port

#887 Add SQL function to query vuln aliases as `JSONB`
  src/main/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDao.java
  src/main/resources/migration/changelog-procedures.xml
  src/main/resources/migration/procedures/function_jsonb-vuln-aliases.sql
Labels: enhancement

#888 Support pagination and improve performance of `/api/v1/vulnerability/source/{source}/vuln/{vuln}/projects` endpoint
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityDao.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: enhancement, breaking change

#886 Improve Vulnerability query endpoints performance
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/RowMapperUtil.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/VulnerabilityRowMapper.java
  src/test/java/org/dependencytrack/persistence/VulnerabilityQueryManagerTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: defect, p2

#891 Fix metrics stored procs to only ever update the latest unchanged record
  src/main/resources/migration/procedures/procedure_update-component-metrics.sql
  src/main/resources/migration/procedures/procedure_update-portfolio-metrics.sql
  src/main/resources/migration/procedures/procedure_update-project-metrics.sql
Labels: defect

#893 Ensure DataNucleus pass-through properties are used in tests
  src/test/java/org/dependencytrack/PersistenceCapableTest.java
Labels: enhancement

#898 Bump Alpine to 3.1.0 and adopt new framework features
  pom.xml
  src/main/docker/logback-json.xml
  src/main/docker/logback.xml
  src/main/resources/application.properties
  src/main/resources/migration/changelog-v5.6.0.xml
  src/main/webapp/WEB-INF/jetty-context.xml
Labels: enhancement

#840 Introduce maintenance tasks; Unify cron and lock duration configs for tasks
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/event/PurlMigrator.java
  src/main/java/org/dependencytrack/event/maintenance/ComponentMetadataMaintenanceEvent.java
  src/main/java/org/dependencytrack/event/maintenance/MetricsMaintenanceEvent.java
  src/main/java/org/dependencytrack/event/maintenance/TagMaintenanceEvent.java
  src/main/java/org/dependencytrack/event/maintenance/VulnerabilityDatabaseMaintenanceEvent.java
  src/main/java/org/dependencytrack/event/maintenance/VulnerabilityScanMaintenanceEvent.java
  src/main/java/org/dependencytrack/event/maintenance/WorkflowMaintenanceEvent.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/WorkflowStateQueryManager.java
  src/main/java/org/dependencytrack/persistence/jdbi/ComponentMetaDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/ConfigPropertyDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/MetricsDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/TagDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityScanDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/WorkflowDao.java
  src/main/java/org/dependencytrack/resources/v1/IntegrationResource.java
  src/main/java/org/dependencytrack/tasks/BaseTaskScheduler.java
  src/main/java/org/dependencytrack/tasks/EpssMirrorTask.java
  src/main/java/org/dependencytrack/tasks/InternalComponentIdentificationTask.java
  src/main/java/org/dependencytrack/tasks/LdapSyncTaskWrapper.java
  src/main/java/org/dependencytrack/tasks/OsvMirrorTask.java
  src/main/java/org/dependencytrack/tasks/RepositoryMetaAnalysisTask.java
  src/main/java/org/dependencytrack/tasks/TaskScheduler.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityAnalysisTask.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityScanCleanupTask.java
  src/main/java/org/dependencytrack/tasks/WorkflowStateCleanupTask.java
  src/main/java/org/dependencytrack/tasks/maintenance/ComponentMetadataMaintenanceTask.java
  src/main/java/org/dependencytrack/tasks/maintenance/MetricsMaintenanceTask.java
  src/main/java/org/dependencytrack/tasks/maintenance/TagMaintenanceTask.java
  src/main/java/org/dependencytrack/tasks/maintenance/VulnerabilityDatabaseMaintenanceTask.java
  src/main/java/org/dependencytrack/tasks/maintenance/VulnerabilityScanMaintenanceTask.java
  src/main/java/org/dependencytrack/tasks/maintenance/WorkflowMaintenanceTask.java
  src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/VulnerabilityMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/VulnerabilityPolicyFetchTask.java
  src/main/java/org/dependencytrack/util/LockProvider.java
  src/main/java/org/dependencytrack/util/TaskUtil.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/PersistenceCapableTest.java
  src/test/java/org/dependencytrack/tasks/RepositoryMetaAnalysisTaskTest.java
  src/test/java/org/dependencytrack/tasks/TaskSchedulerTest.java
  src/test/java/org/dependencytrack/tasks/VulnerabilityScanCleanupTaskTest.java
  src/test/java/org/dependencytrack/tasks/maintenance/ComponentMetadataMaintenanceTaskTest.java
  src/test/java/org/dependencytrack/tasks/maintenance/MetricsMaintenanceTaskTest.java
  src/test/java/org/dependencytrack/tasks/maintenance/TagMaintenanceTaskTest.java
  src/test/java/org/dependencytrack/tasks/maintenance/VulnerabilityDatabaseMaintenanceTaskTest.java
  src/test/java/org/dependencytrack/tasks/maintenance/VulnerabilityScanMaintenanceTaskTest.java
  src/test/java/org/dependencytrack/tasks/maintenance/WorkflowMaintenanceTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/AbstractMetricsUpdateTaskTest.java
Labels: enhancement, technical debt, breaking change

#900 Fix mapping of `PURL` column to vulnerable components
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityDao.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: defect

#906 Remove Alpine `PersistenceInitializer`
  src/main/java/alpine/server/persistence/PersistenceInitializer.java
  src/main/webapp/WEB-INF/web.xml
Labels: technical debt

#905 Replace Redpanda testcontainers with Apache Kafka native
  pom.xml
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/dev/DevServicesInitializer.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/event/kafka/processor/api/ProcessorManagerTest.java
Labels: technical debt

#902 Fix Maven warning about missing `exec-maven-plugin` version
  pom.xml
Labels: technical debt

#901 Fix `Attempt to use transient object as parameter in query` warning in test
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: defect

#866 Port: Replace author with authors
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/model/sqlmapping/ComponentProjection.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityDao.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/resources/migration/changelog-v5.6.0.xml
  src/test/java/org/dependencytrack/persistence/ComponentQueryManangerPostgresTest.java
  src/test/java/org/dependencytrack/persistence/converter/ToolsJsonConverterTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-issue3936-author.json
  src/test/resources/unit/bom-issue3936-authors.json
  src/test/resources/unit/bom-issue3936-both.json
Labels: enhancement, v4-port

#904 Remove `alpine.` prefix from Kafka processor properties
  src/main/java/org/dependencytrack/event/kafka/processor/api/ProcessorManager.java
  src/main/java/org/dependencytrack/util/ConfigUtil.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/event/kafka/processor/api/ProcessorManagerTest.java
  src/test/java/org/dependencytrack/util/ConfigUtilTest.java
Labels: technical debt, breaking change

#910 Issue 1428 : remove deprecated code
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/TagResource.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: technical debt, breaking change

#911 Port : Handle existing duplicate component properties & empty component and service names
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect, v4-port

#913 Port : customizable login page
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/resources/v1/ConfigPropertyResource.java
  src/test/java/org/dependencytrack/resources/v1/ConfigPropertyResourceTest.java
Labels: enhancement, v4-port

#912 Migrate `DIRECT_DEPENDENCIES` from `TEXT` to `JSONB`
  pom.xml
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyQueryManager.java
  src/main/resources/migration/changelog-v5.6.0.xml
  src/test/java/org/dependencytrack/persistence/ComponentQueryManangerPostgresTest.java
Labels: enhancement

#915 Fix `/api/v1/event/token/{uuid}` not checking workflow states
  src/main/java/org/dependencytrack/persistence/jdbi/WorkflowDao.java
  src/main/java/org/dependencytrack/resources/v1/EventResource.java
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/EventResourceTest.java
Labels: defect

#914 Port : Support inclusion/exclusion of projects from BOM validation with tags
  src/main/java/org/dependencytrack/model/BomValidationMode.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/resources/v1/AbstractConfigPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/resources/migration/changelog-v5.6.0.xml
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ConfigPropertyResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
Labels: enhancement, v4-port

#805 Introduce plugin system to deal with provider config and lifecycle
  src/main/java/org/dependencytrack/common/MdcKeys.java
  src/main/java/org/dependencytrack/plugin/ConfigRegistryImpl.java
  src/main/java/org/dependencytrack/plugin/PluginInitializer.java
  src/main/java/org/dependencytrack/plugin/PluginManager.java
  src/main/java/org/dependencytrack/plugin/api/ConfigDefinition.java
  src/main/java/org/dependencytrack/plugin/api/ConfigRegistry.java
  src/main/java/org/dependencytrack/plugin/api/ConfigSource.java
  src/main/java/org/dependencytrack/plugin/api/ExtensionFactory.java
  src/main/java/org/dependencytrack/plugin/api/ExtensionPoint.java
  src/main/java/org/dependencytrack/plugin/api/ExtensionPointMetadata.java
  src/main/java/org/dependencytrack/plugin/api/Plugin.java
  src/main/resources/META-INF/services/org.dependencytrack.plugin.api.ExtensionPointMetadata
  src/main/resources/META-INF/services/org.dependencytrack.plugin.api.Plugin
  src/main/webapp/WEB-INF/web.xml
  src/test/java/org/dependencytrack/PersistenceCapableTest.java
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/plugin/ConfigRegistryImplTest.java
  src/test/java/org/dependencytrack/plugin/DummyPlugin.java
  src/test/java/org/dependencytrack/plugin/DummyTestExtension.java
  src/test/java/org/dependencytrack/plugin/DummyTestExtensionFactory.java
  src/test/java/org/dependencytrack/plugin/PluginManagerTest.java
  src/test/java/org/dependencytrack/plugin/PluginManagerTestUtil.java
  src/test/java/org/dependencytrack/plugin/TestExtensionPoint.java
  src/test/java/org/dependencytrack/plugin/TestExtensionPointMetadata.java
  src/test/resources/META-INF/services/org.dependencytrack.plugin.api.ExtensionPointMetadata
  src/test/resources/META-INF/services/org.dependencytrack.plugin.api.Plugin
Labels: enhancement

#917 Enable `reWriteBatchedInserts` Postgres JDBC driver option in tests
  src/main/java/org/dependencytrack/dev/DevServicesInitializer.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/PostgresTestContainer.java
Labels: enhancement

#919 Fix `PortfolioMetricsUpdateTask` refreshing too many project metrics concurrently
  src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java
  src/test/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTaskTest.java
Labels: defect

#920 Port: Fix infinite recursion during policy condition serialization
  src/main/java/org/dependencytrack/resources/v1/PolicyConditionResource.java
  src/test/java/org/dependencytrack/resources/v1/PolicyConditionResourceTest.java
Labels: defect, v4-port

#922 Port : Include team name in audit trail for API-submitted audit changes
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
  src/test/java/org/dependencytrack/resources/v1/AnalysisResourceTest.java
Labels: enhancement, v4-port

#924 Port test cases
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: v4-port

#926 Port: Ensure no unique constraint violation for `ProjectMetadata`
  src/main/java/org/dependencytrack/common/MdcKeys.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/tasks/CloneProjectTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/java/org/dependencytrack/tasks/CloneProjectTaskTest.java
Labels: defect, v4-port

#927 Port: Fix `directDependencies` of cloned projects referring to original component UUIDs
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect, v4-port

#928 Port : Add option to test notification publisher
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/main/java/org/dependencytrack/util/NotificationUtil.java
  src/test/java/org/dependencytrack/resources/v1/NotificationPublisherResourceTest.java
Labels: enhancement, v4-port

#929 Fix `authors` column failing to be mapped for `/api/v1/component/project/{uuid}` endpoint
  src/main/java/org/dependencytrack/model/ComponentMetaInformation.java
  src/main/java/org/dependencytrack/model/sqlmapping/ComponentProjection.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourcePostgresTest.java
Labels: defect

#934 Fix `/api/v1/vulnerability/source/{source}/vuln/{vuln}` returning all vulnerable components
  src/main/java/org/dependencytrack/model/sqlmapping/ComponentProjection.java
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/VulnerabilityRowMapper.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/VulnerableSoftwareRowMapper.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: defect
