Repository DependencyTrack/hyades-apiserver, pull requests merged in 2024-05, with the labels that each got.

#670 Start Jersey `TestContainer` once per class vs. once per test method
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/test/java/org/dependencytrack/JerseyTestRule.java
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/event/kafka/processor/ProcessedVulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/event/kafka/processor/RepositoryMetaResultProcessorTest.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityMirrorProcessorTest.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/resources/v1/AnalysisResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/BadgeResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/CalculatorResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourcePostgresTest.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ConfigPropertyResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/CweResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/DependencyGraphResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/LdapResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/LicenseResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/NotificationPublisherResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/OidcResourceAuthenticatedTest.java
  src/test/java/org/dependencytrack/resources/v1/OidcResourceUnauthenticatedTest.java
  src/test/java/org/dependencytrack/resources/v1/OsvEcosystemResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/PolicyConditionResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/PolicyResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/PolicyViolationResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectPropertyResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/RepositoryResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/UserResourceAuthenticatedTest.java
  src/test/java/org/dependencytrack/resources/v1/UserResourceUnauthenticatedTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ViolationAnalysisResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityPolicyBundleResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/WorkflowResourceTest.java
Labels: dx, v4-port

#668 Config cleanup
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/kafka/KafkaProducerInitializer.java
  src/main/java/org/dependencytrack/event/kafka/processor/api/ProcessorManager.java
  src/main/java/org/dependencytrack/persistence/migration/MigrationInitializer.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/persistence/migration/MigrationInitializerTest.java
Labels: technical debt

#659 Port: Return processing token when cloning project
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/EventResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: v4-port

#678 Prevent concurrent processing of multiple BOMs for the same project
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/util/LockProvider.java
  src/main/java/org/dependencytrack/util/WaitingLockConfiguration.java
  src/main/java/org/dependencytrack/util/WaitingLockProvider.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: enhancement

#681 Encode length constraints for vuln policy fields in JSON schema
  src/main/java/org/dependencytrack/model/VulnerabilityPolicy.java
  src/main/resources/migration/changelog-v5.5.0.xml
  src/main/resources/schema/vulnerability-policy-v1.schema.json
Labels: enhancement

#680 Add `KAFKA_BOOTSTRAP_SERVERS` to `Jetty` run configuration
  .idea/runConfigurations/Jetty.xml
Labels: dx

#679 Track request duration metrics
  pom.xml
  src/main/java/org/dependencytrack/filters/JerseyMetricsApplicationEventListener.java
  src/main/java/org/dependencytrack/observability/MeterRegistryCustomizer.java
Labels: enhancement

#687 Bump `cvss-calculator` to `1.4.3`
  pom.xml
  src/main/java/org/dependencytrack/parser/dependencytrack/ModelConverterCdxToVuln.java
  src/main/java/org/dependencytrack/resources/v1/CalculatorResource.java
  src/test/java/org/dependencytrack/resources/v1/CalculatorResourceTest.java
Labels: dependencies, java

#689 Port: ACL: Add projects to team should only show not yet added projects
  src/main/java/org/dependencytrack/persistence/ProjectQueryFilterBuilder.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
Labels: enhancement, v4-port
