Repository DependencyTrack/hyades-apiserver, pull requests merged in 2024-02, with the labels that each got.

#550 Backport minor bug fixes
  src/main/docker/Dockerfile
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXVexImporter.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
  src/main/resources/templates/notification/publisher/slack.peb
  src/test/java/org/dependencytrack/model/ProjectTest.java
  src/test/java/org/dependencytrack/policy/cel/compat/VersionDistanceCelPolicyEvaluatorTest.java
  src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java
Labels: enhancement

#556 Fix policy bundle sync being trigger-able even though the feature is disabled
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResource.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResourceTest.java
Labels: bug

#552 Implement foundational API for parallel-consumer based Kafka processors
  pom.xml
  src/main/java/org/dependencytrack/common/MdcKeys.java
  src/main/java/org/dependencytrack/event/kafka/processor/ProcessorInitializer.java
  src/main/java/org/dependencytrack/event/kafka/processor/ProcessorsHealthCheck.java
  src/main/java/org/dependencytrack/event/kafka/processor/api/AbstractProcessingStrategy.java
  src/main/java/org/dependencytrack/event/kafka/processor/api/BatchProcessingStrategy.java
  src/main/java/org/dependencytrack/event/kafka/processor/api/BatchProcessor.java
  src/main/java/org/dependencytrack/event/kafka/processor/api/ProcessingStrategy.java
  src/main/java/org/dependencytrack/event/kafka/processor/api/Processor.java
  src/main/java/org/dependencytrack/event/kafka/processor/api/ProcessorManager.java
  src/main/java/org/dependencytrack/event/kafka/processor/api/ProcessorProperties.java
  src/main/java/org/dependencytrack/event/kafka/processor/api/SingleRecordProcessingStrategy.java
  src/main/java/org/dependencytrack/event/kafka/processor/exception/ProcessingException.java
  src/main/java/org/dependencytrack/event/kafka/processor/exception/RetryableProcessingException.java
  src/main/java/org/dependencytrack/event/kafka/streams/KafkaStreamsInitializer.java
  src/main/java/org/dependencytrack/event/kafka/streams/KafkaStreamsTopologyFactory.java
  src/main/java/org/dependencytrack/event/kafka/streams/exception/AbstractThresholdBasedExceptionHandler.java
  src/main/java/org/dependencytrack/event/kafka/streams/exception/KafkaStreamsDeserializationExceptionHandler.java
  src/main/java/org/dependencytrack/event/kafka/streams/exception/KafkaStreamsProductionExceptionHandler.java
  src/main/java/org/dependencytrack/event/kafka/streams/exception/KafkaStreamsUncaughtExceptionHandler.java
  src/main/java/org/dependencytrack/event/kafka/streams/processor/DelayedBomProcessedNotificationProcessor.java
  src/main/java/org/dependencytrack/event/kafka/streams/processor/MirrorVulnerabilityProcessor.java
  src/main/java/org/dependencytrack/event/kafka/streams/processor/RepositoryMetaResultProcessor.java
  src/main/java/org/dependencytrack/event/kafka/streams/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/health/KafkaStreamsHealthCheck.java
  src/main/java/org/dependencytrack/util/NotificationUtil.java
  src/main/resources/application.properties
  src/main/webapp/WEB-INF/web.xml
  src/test/java/org/dependencytrack/event/kafka/processor/AbstractProcessorTest.java
  src/test/java/org/dependencytrack/event/kafka/processor/api/ProcessorManagerTest.java
  src/test/java/org/dependencytrack/event/kafka/streams/KafkaStreamsDelayedBomProcessedNotificationTest.java
  src/test/java/org/dependencytrack/event/kafka/streams/KafkaStreamsPostgresTest.java
  src/test/java/org/dependencytrack/event/kafka/streams/KafkaStreamsTest.java
  src/test/java/org/dependencytrack/event/kafka/streams/KafkaStreamsTopologyTest.java
  src/test/java/org/dependencytrack/event/kafka/streams/exception/KafkaStreamsDeserializationExceptionHandlerTest.java
  src/test/java/org/dependencytrack/event/kafka/streams/exception/KafkaStreamsProductionExceptionHandlerTest.java
  src/test/java/org/dependencytrack/event/kafka/streams/exception/KafkaStreamsUncaughtExceptionHandlerTest.java
  src/test/java/org/dependencytrack/event/kafka/streams/processor/MirrorVulnerabilityProcessorTest.java
  src/test/java/org/dependencytrack/event/kafka/streams/processor/RepositoryMetaResultProcessorTest.java
  src/test/java/org/dependencytrack/event/kafka/streams/processor/VulnerabilityScanResultProcessorTest.java
Labels: enhancement

#537 Implement `is_exclusive_dependency_of` function for CEL expressions
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyScriptHost.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyScriptVersValidationVisitor.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyEngineTest.java
Labels: enhancement

#551 Create GIN index on `"COMPONENT"."DIRECT_DEPENDENCIES"` to support dependency graph traversal
  src/main/resources/migration/changelog-v5.3.0.xml
Labels: enhancement

#561 Allow usage of separate database user for running migrations
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/persistence/migration/MigrationInitializer.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/persistence/migration/MigrationInitializerTest.java
Labels: enhancement

#565 Update `dbschema-generate.sh` schema to use Liquibase
  dev/scripts/dbschema-generate.sh
  pom.xml
Labels: enhancement

#572 Add strict token permissions in GH workflows and update image to Java 21 JRE
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-build.yaml
  .github/workflows/ci-publish.yaml
  .github/workflows/ci-release.yaml
  .github/workflows/ci-test.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/lock.yaml
  src/main/docker/Dockerfile
Labels: enhancement

#575 Reduce verbosity of Maven in CI
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-test.yaml
Labels: enhancement

#574 Fix GitHub Actions workflow permissions
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-build.yaml
  .github/workflows/ci-publish.yaml
  .github/workflows/ci-release.yaml
Labels: bug

#570 Add supplier manufacturer support
  src/main/java/org/dependencytrack/model/Classifier.java
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/OrganizationalContact.java
  src/main/java/org/dependencytrack/model/OrganizationalEntity.java
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/model/ProjectMetadata.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/converter/AbstractJsonConverter.java
  src/main/java/org/dependencytrack/persistence/converter/OrganizationalContactsJsonConverter.java
  src/main/java/org/dependencytrack/persistence/converter/OrganizationalEntityJsonConverter.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/resources/META-INF/persistence.xml
  src/main/resources/migration/changelog-v5.3.0.xml
  src/test/java/org/dependencytrack/persistence/converter/OrganizationalContactsJsonConverterTest.java
  src/test/java/org/dependencytrack/persistence/converter/OrganizationalEntityJsonConverterTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-1.xml
Labels: enhancement

#577 Fix FK constraint violation when deleting project with associated metadata
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/persistence/ProjectQueryManagerTest.java
Labels: bug

#578 Fix partial `license` objects being returned by `/api/v1/component` for components with unresolved license
  src/main/java/org/dependencytrack/model/sqlmapping/ComponentProjection.java
Labels: bug

#584 Bump dependencies and re-enable checkstyle
  .checkstyle.xml
  pom.xml
  src/main/java/org/dependencytrack/integrations/kenna/KennaDataTransformer.java
  src/main/java/org/dependencytrack/model/MetaModel.java
  src/main/java/org/dependencytrack/model/VulnerableSoftware.java
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
  src/main/java/org/dependencytrack/resources/v1/ConfigPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/tasks/InternalComponentIdentificationTask.java
  src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/blobstorage/S3StorageHandler.java
Labels: dependencies, java

#590 Handle direct dependency relationships in `is_exclusive_dependency_of`
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyEngineTest.java
Labels: bug

#571 Fix notification templates
  src/main/resources/templates/notification/publisher/cswebex.peb
  src/main/resources/templates/notification/publisher/email.peb
  src/main/resources/templates/notification/publisher/jira.peb
  src/main/resources/templates/notification/publisher/mattermost.peb
  src/main/resources/templates/notification/publisher/msteams.peb
  src/main/resources/templates/notification/publisher/slack.peb
  src/main/resources/templates/notification/publisher/webhook.peb
Labels: bug

#589 Rename topic prefix config
  DEVELOPING.md
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/event/kafka/KafkaTopicsTest.java
Labels: enhancement

#592 Fix `ClassCastException` when updating an existing `ProjectMetadata#authors` field
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-issue3309.json
Labels: bug

#595 Bump Redpanda to v23.3.6
  src/test/java/org/dependencytrack/event/kafka/processor/api/ProcessorManagerTest.java
  src/test/java/org/dependencytrack/event/kafka/streams/KafkaStreamsTest.java
Labels: dependencies, docker

#580 Replace json string with proto in Version Distance Cel Policy
  src/main/java/org/dependencytrack/model/VersionDistance.java
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
  src/main/java/org/dependencytrack/policy/cel/compat/VersionDistanceCelScriptBuilder.java
  src/main/java/org/dependencytrack/policy/cel/definition/CelPolicyTypes.java
  src/main/proto/org/dependencytrack/policy/v1/policy.proto
  src/test/java/org/dependencytrack/model/VersionDistanceTest.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyEngineTest.java
Labels: enhancement

#596 Fix NPE in `IntegrityMetaInitializerTask`
  src/main/java/org/dependencytrack/tasks/IntegrityMetaInitializerTask.java
  src/test/java/org/dependencytrack/tasks/IntegrityMetaInitializerTaskTest.java
Labels: bug
