Repository DependencyTrack/hyades-apiserver, pull requests merged in 2024-01, with the labels that each got.

#511 Fix inconsistent `AnalysisComment` ordering in case of equal `timestamp` values
  src/main/java/org/dependencytrack/model/Analysis.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
Labels: bug

#506 Add PROJECT_AUDIT_CHANGE notification on policy eval
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/NotificationSubjectProjectAuditChangeRowMapper.java
  src/main/java/org/dependencytrack/util/NotificationUtil.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDaoTest.java
Labels: enhancement

#512 Handle reversal of analyses applied via vulnerability policy
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/model/Analysis.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityPolicyQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
  src/main/java/org/dependencytrack/util/AnalysisCommentFormatter.java
  src/main/java/org/dependencytrack/util/AnalysisCommentUtil.java
  src/main/java/org/dependencytrack/util/VulnerabilityPolicyUtil.java
  src/main/resources/migration/changelog-v5.3.0.xml
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/persistence/VulnerabilityPolicyQueryManagerTest.java
Labels: enhancement

#515 Fix suppression not being reverted upon policy deletion
  src/main/java/org/dependencytrack/persistence/VulnerabilityPolicyQueryManager.java
  src/test/java/org/dependencytrack/persistence/VulnerabilityPolicyQueryManagerTest.java
Labels: bug

#516 Support bearer auth for policy bundle server
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/blobstorage/NginxStorageHandler.java
  src/main/java/org/dependencytrack/util/VulnerabilityPolicyUtil.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/VulnerabilityPolicyFetchTaskTest.java
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/blobstorage/NginxStorageHandlerTest.java
  src/test/java/org/dependencytrack/util/VulnerabilityPolicyUtilTest.java
Labels: enhancement

#519 Fix `validFrom` and `validUntil` not being considered when evaluating vuln policies
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityPolicyQueryManager.java
  src/main/java/org/dependencytrack/policy/vulnerability/DatabaseVulnerabilityPolicyProvider.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/persistence/VulnerabilityPolicyQueryManagerTest.java
Labels: bug

#523 Close response to prevent resource leakage
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/VulnerabilityPolicyFetchTask.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/blobstorage/NginxStorageHandler.java
Labels: bug

#527 Add capability to use regular expressions and `vers` ranges in dependency graph traversal
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyScriptHost.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyScriptVersValidationVisitor.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyScriptVisitor.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyEngineTest.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyScriptHostTest.java
Labels: enhancement

#530 Fix NPE in `PROJECT_AUDIT_CHANGE` notification creation
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/util/NotificationUtil.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
Labels: bug

#528 Add workflow step for policy bundle sync
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/VulnerabilityPolicyFetchEvent.java
  src/main/java/org/dependencytrack/model/WorkflowStatus.java
  src/main/java/org/dependencytrack/model/WorkflowStep.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResource.java
  src/main/java/org/dependencytrack/tasks/vulnerabilitypolicy/VulnerabilityPolicyFetchTask.java
  src/test/java/org/dependencytrack/resources/v1/AbstractPostgresResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResourceTest.java
  src/test/java/org/dependencytrack/tasks/vulnerabilitypolicy/VulnerabilityPolicyFetchTaskTest.java
Labels: enhancement

#532 Bump `versatile` to `0.4.0`
  pom.xml
Labels: dependencies, java

#513 Add pagination and ordering boilerplate for JDBI
  src/main/java/org/dependencytrack/persistence/Ordering.java
  src/main/java/org/dependencytrack/persistence/jdbi/binding/DefineOrdering.java
  src/main/java/org/dependencytrack/persistence/jdbi/binding/DefinePagination.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/PaginatedResultRowReducer.java
  src/test/java/org/dependencytrack/persistence/jdbi/JdbiTestUtil.java
  src/test/java/org/dependencytrack/persistence/jdbi/binding/DefineOrderingTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/binding/DefinePaginationTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/mapping/PaginatedResultRowReducerTest.java
Labels: enhancement

#520 Jdbi queries for Vulnerability Policies
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityPolicyDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/RowMapperUtil.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/VulnPolicyAnalysisArgumentFactory.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/VulnPolicyRatingsArgumentFactory.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/VulnerabilityPolicyRowMapper.java
  src/main/java/org/dependencytrack/policy/cel/CelVulnerabilityPolicyEvaluator.java
  src/main/java/org/dependencytrack/policy/vulnerability/VulnerabilityPolicy.java
  src/test/java/org/dependencytrack/persistence/jdbi/VulnerabilityPolicyDaoTest.java
  src/test/java/org/dependencytrack/policy/cel/CelVulnerabilityPolicyEvaluatorTest.java
Labels: enhancement

#539 Add support for github meta analyzer
  src/main/java/org/dependencytrack/model/RepositoryType.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java
  src/test/java/org/dependencytrack/resources/v1/RepositoryResourceTest.java
Labels: enhancement

#536 Add LogSuccessfulPublish parameter NotificationRule
  src/main/java/org/dependencytrack/model/NotificationRule.java
  src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
  src/main/resources/migration/changelog-v5.3.0.xml
  src/test/java/org/dependencytrack/model/NotificationRuleTest.java
Labels: enhancement

#544 Update component metrics in project metrics update procedure
  src/main/java/org/dependencytrack/event/ProjectMetricsUpdateEvent.java
  src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java
  src/main/resources/migration/procedures/procedure_update-project-metrics.sql
  src/test/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTaskTest.java
Labels: enhancement

#541 Bump Redpanda to v23.3.3
  src/test/java/org/dependencytrack/event/kafka/KafkaStreamsPostgresTest.java
  src/test/java/org/dependencytrack/event/kafka/KafkaStreamsTest.java
Labels: dependencies

#543 Declare DB functions as `language sql` and `immutable`
  src/main/resources/migration/procedures/function_calc-risk-score.sql
  src/main/resources/migration/procedures/function_calc-severity.sql
  src/main/resources/migration/procedures/function_cvssv2-to-severity.sql
  src/main/resources/migration/procedures/function_cvssv3-to-severity.sql
  src/test/java/org/dependencytrack/tasks/InternalComponentIdentificationTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/AbstractMetricsUpdateTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/VulnerabilityMetricsUpdateTaskTest.java
  src/test/resources/shedlock_h2.sql
Labels: enhancement

#548 Fix broken component filter in project view
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourcePostgresTest.java
Labels: bug

#547 Remove CPE table and its code usage
  src/main/java/org/dependencytrack/event/kafka/processor/MirrorVulnerabilityProcessor.java
  src/main/java/org/dependencytrack/model/Cpe.java
  src/main/java/org/dependencytrack/parser/nvd/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/main/java/org/dependencytrack/persistence/LicenseQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/ServiceComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/ServiceResource.java
  src/main/resources/META-INF/persistence.xml
  src/main/resources/migration/changelog-v5.3.0.xml
  src/test/java/org/dependencytrack/model/CpeTest.java
Labels: enhancement
