Repository DependencyTrack/hyades-apiserver, pull requests merged in 2024-11, with the labels that each got.

#970 Quick fix : component author column mapping
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/OrganizationalContactMapper.java
  src/test/java/org/dependencytrack/persistence/VulnerabilityQueryManagerTest.java
Labels: defect

#971 Quick-fix : sql query to add tags while fetching vulnerabilities
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/mapping/VulnerabilityRowMapper.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: defect, size/S

#977 Port : Fix redundant ConfigProperty queries in BadgeResource
  src/main/java/org/dependencytrack/resources/v1/BadgeResource.java
Labels: enhancement, v4-port

#978 Port : Fix CPE not being imported from CycloneDX metadata.component
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-1.xml
Labels: defect, v4-port

#975 Bump various dependencies
  dev/scripts/dbschema-generate.sh
  pom.xml
  src/main/java/org/dependencytrack/persistence/migration/MigrationInitializer.java
  src/test/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizerTest.java
Labels: dependencies

#984 Replace update workflow state methods with DAO queries
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/WorkflowStateQueryManager.java
  src/main/java/org/dependencytrack/persistence/jdbi/WorkflowDao.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/persistence/WorkflowQueryManagerTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/WorkflowDaoTest.java
Labels: enhancement

#979 Fix missing `ConfigPropertyConstants` values for vulnerability mirroring properties
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/resources/migration/changelog-v5.6.0.xml
Labels: defect
