Repository DependencyTrack/hyades-apiserver, pull requests merged in 2024-04, with the labels that each got.

#643 Ingest BOM generation timestamp
  src/main/java/org/dependencytrack/model/Bom.java
  src/main/java/org/dependencytrack/persistence/BomQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyDao.java
  src/main/java/org/dependencytrack/policy/cel/persistence/CelPolicyProjectRowMapper.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/proto/org/dependencytrack/policy/v1/policy.proto
  src/main/resources/migration/changelog-v5.5.0.xml
  src/test/java/org/dependencytrack/model/ProjectTest.java
  src/test/java/org/dependencytrack/persistence/ProjectQueryManagerTest.java
  src/test/java/org/dependencytrack/policy/cel/CelPolicyEngineTest.java
  src/test/java/org/dependencytrack/policy/cel/persistence/CelPolicyDaoTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-metadata-timestamp.json
Labels: enhancement

#649 Bump dependencies
  pom.xml
Labels: dependencies, java

#651 Run builds and CI on feature branches
  .github/workflows/_meta-build.yaml
  .github/workflows/buf.yml
  .github/workflows/ci-build.yaml
  .github/workflows/ci-publish.yaml
  .github/workflows/ci-test.yaml
Labels: enhancement

#633 Enrich `application.properties` with annotations
  .github/workflows/config-docs-update.yml
  src/main/resources/application.properties
Labels: documentation

#657 Skip Checkstyle for `Jetty` and `DataNucleus Enhance` run configs
  .idea/runConfigurations/Checkstyle.xml
  .idea/runConfigurations/DataNucleus Enhance.run.xml
  .idea/runConfigurations/Jetty.xml
Labels: dx

#654 Issue 947 : Add support for manual vulnerability tags
  src/main/java/org/dependencytrack/model/Tag.java
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/main/resources/migration/changelog-v5.5.0.xml
  src/test/java/org/dependencytrack/persistence/TagQueryManagerTest.java
  src/test/java/org/dependencytrack/persistence/VulnerabilityQueryManagerTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: enhancement

#652 Publish histograms for event processing durations
  src/main/java/org/dependencytrack/common/MdcKeys.java
  src/main/java/org/dependencytrack/observability/MeterRegistryCustomizer.java
  src/main/java/org/dependencytrack/policy/cel/CelPolicyEngine.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTask.java
  src/main/java/org/dependencytrack/tasks/metrics/VulnerabilityMetricsUpdateTask.java
  src/main/resources/META-INF/services/alpine.common.metrics.MeterRegistryCustomizer
Labels: enhancement

#665 Bump Redpanda to v23.3.13
  src/test/java/org/dependencytrack/event/kafka/processor/api/ProcessorManagerTest.java
Labels: dependencies, docker

#666 Bump Temurin base image to 21.0.3_9
  src/main/docker/Dockerfile
Labels: dependencies, docker
