Repository DependencyTrack/hyades-apiserver, pull requests merged in 2024-07, with the labels that each got.

#770 Bump nimbusds oauth version
  pom.xml
  src/main/java/org/dependencytrack/model/VulnerabilityAlias.java
Labels: dependencies, java

#783 Upgrade wiremock and kotlin versions
  pom.xml
Labels: dependencies, java

#787 Bump Redpanda to v24.1.11
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/event/kafka/processor/api/ProcessorManagerTest.java
Labels: dependencies, docker

#795 Port : log warning when dependency graph is missing the root node
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
Labels: enhancement, v4-port

#798 Rename Kafka topic prefix config
  DEVELOPING.md
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/event/kafka/KafkaTopics.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/event/kafka/KafkaTopicsTest.java
Labels: defect, breaking change

#799 Add breaking changes category to release notes
  .github/release.yml
Labels: documentation

#801 Add option to exit after running database migrations
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/java/org/dependencytrack/persistence/migration/MigrationInitializer.java
  src/main/resources/application.properties
Labels: enhancement

#806 Port : Fix JDOUserException when multiple licenses match a component's licence
  src/main/java/org/dependencytrack/persistence/LicenseQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: defect, v4-port

#815 Replace manual transaction commits with `callInTransaction`
  src/main/java/org/dependencytrack/persistence/MetricsQueryManager.java
  src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/java/org/dependencytrack/tasks/WorkflowStateCleanupTask.java
  src/main/resources/logback.xml
Labels: enhancement, v4-port

#818 Deal with JUnit 4 version no longer being inherited from `alpine-parent`
  pom.xml
Labels: defect

#800 Permission deconstruction
  src/main/java/org/dependencytrack/auth/Permissions.java
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
  src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/resources/v1/ConfigPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/main/java/org/dependencytrack/resources/v1/IntegrationResource.java
  src/main/java/org/dependencytrack/resources/v1/LdapResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseGroupResource.java
  src/main/java/org/dependencytrack/resources/v1/LicenseResource.java
  src/main/java/org/dependencytrack/resources/v1/MetricsResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
  src/main/java/org/dependencytrack/resources/v1/OidcResource.java
  src/main/java/org/dependencytrack/resources/v1/PermissionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyConditionResource.java
  src/main/java/org/dependencytrack/resources/v1/PolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectPropertyResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/java/org/dependencytrack/resources/v1/RepositoryResource.java
  src/main/java/org/dependencytrack/resources/v1/ServiceResource.java
  src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  src/main/java/org/dependencytrack/resources/v1/UserResource.java
  src/main/java/org/dependencytrack/resources/v1/VexResource.java
  src/main/java/org/dependencytrack/resources/v1/ViolationAnalysisResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityPolicyBundleResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityPolicyResource.java
  src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  src/test/java/org/dependencytrack/auth/PermissionsTest.java
  src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
Labels: enhancement
