Repository DependencyTrack/hyades-apiserver, pull requests merged in 2025-01, with the labels that each got.

#1013 Reduce logging noise of `PluginManager`
  src/main/java/org/dependencytrack/plugin/PluginManager.java
Labels: enhancement

#1011 Remove usages of Guava's `Suppliers.memoize`
  src/main/java/org/dependencytrack/common/ClusterInfo.java
  src/main/java/org/dependencytrack/util/InternalComponentIdentifier.java
Labels: technical debt

#1030 Port : Fix NullPointerException when fetching findings
  src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java
Labels: defect, v4-port

#1031 Port : Fix incorrect CWE schema in OpenAPI spec
  src/main/java/org/dependencytrack/model/Vulnerability.java
Labels: defect, v4-port

#1032 Port : Fix nullable metrics fields having getters of primitive type
  src/main/java/org/dependencytrack/model/DependencyMetrics.java
  src/main/java/org/dependencytrack/model/PortfolioMetrics.java
  src/main/java/org/dependencytrack/model/ProjectMetrics.java
Labels: defect, v4-port

#1034 Port : Fix NPE when cloning projects with broken dependency graph
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect, v4-port

#1033 Port : Add cyclonedx json media type when exporting components
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
Labels: defect, v4-port

#1035 Create missing unique index on `PROJECT_METADATA.PROJECT_ID`
  src/main/resources/migration/changelog-v5.6.0.xml
Labels: defect

#1036 Re-add script to generate DB schema migration SQL
  dev/scripts/dbschema-generate-migration.sh
Labels: dx

#1037 Exclude `NULL`s from component hash indexes
  src/main/resources/migration/changelog-v5.6.0.xml
Labels: enhancement

#1038 Port : Bump Alpine to 3.1.2
  pom.xml
Labels: dependencies, v4-port

#1024 Suppress rejected vulnerabilities (records with empty data) by SNYK
  src/main/java/org/dependencytrack/event/kafka/KafkaEventConverter.java
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/main/java/org/dependencytrack/util/NotificationUtil.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
Labels: enhancement

#949 Port : Global Audit View: Policy Violations
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/resources/v1/PolicyViolationResource.java
  src/test/java/org/dependencytrack/resources/v1/PolicyViolationResourceTest.java
Labels: enhancement, v4-port

#1041 Port : Fix broken pagination in /api/v1/cwe endpoint
  src/main/java/org/dependencytrack/parser/common/resolver/CweResolver.java
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/CweResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/PolicyViolationResourceTest.java
Labels: defect, v4-port

#1043 Port : Fix onlyOutdated ungrouped component filtering
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/test/java/org/dependencytrack/persistence/ComponentQueryManangerPostgresTest.java
Labels: defect, v4-port

#1044 Port : Add component SWID tag ID in project cloning + fix component de-duplication
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/resources/unit/bom-issue4455.json
Labels: defect, v4-port

#1045 Port : fix notification rule test for rule not found
  src/main/java/org/dependencytrack/resources/v1/NotificationPublisherResource.java
  src/test/java/org/dependencytrack/resources/v1/NotificationPublisherResourceTest.java
Labels: defect, v4-port

#1048 Port : Fix incompatibility of swagger-core with newer jackson-databind versions
  pom.xml
Labels: defect, v4-port
