Repository DependencyTrack/hyades-apiserver, pull requests merged in 2025-03, with the labels that each got.

#1071 Accept BOM uploads in Protobuf format
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidator.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverterProto.java
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDxValidatorTest.java
  src/test/java/org/dependencytrack/parser/cyclonedx/util/ModelConverterProtoTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: enhancement

#1081 Add risk rating vectors in findings response
  src/main/java/org/dependencytrack/model/Finding.java
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
  src/test/java/org/dependencytrack/integrations/FindingPackagingFormatTest.java
  src/test/java/org/dependencytrack/model/FindingTest.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: enhancement

#1073 Fix `BOM_VALIDATION_FAILED` notifications containing the full BOM content
  src/main/java/org/dependencytrack/resources/v1/BomResource.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
Labels: defect

#1072 Ingest component occurrences
  pom.xml
  src/main/java/org/dependencytrack/model/Component.java
  src/main/java/org/dependencytrack/model/ComponentOccurrence.java
  src/main/java/org/dependencytrack/model/sqlmapping/ComponentProjection.java
  src/main/java/org/dependencytrack/parser/cyclonedx/util/ModelConverter.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/jdbi/ApiRequestConfig.java
  src/main/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizer.java
  src/main/java/org/dependencytrack/persistence/jdbi/ComponentDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/DefineApiProjectAclCondition.java
  src/main/java/org/dependencytrack/persistence/jdbi/JdbiFactory.java
  src/main/java/org/dependencytrack/persistence/jdbi/ProjectDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityDao.java
  src/main/java/org/dependencytrack/resources/v1/AbstractApiResource.java
  src/main/java/org/dependencytrack/resources/v1/ComponentResource.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/main/resources/META-INF/persistence.xml
  src/main/resources/migration/changelog-v5.6.0.xml
  src/test/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizerTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourcePostgresTest.java
  src/test/java/org/dependencytrack/resources/v1/ComponentResourceTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
Labels: enhancement

#1086 Don't throw when ordering API params are provided but DAO method has no order-able columns list
  src/main/java/org/dependencytrack/persistence/jdbi/ApiRequestConfig.java
  src/main/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizer.java
  src/test/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizerTest.java
Labels: defect

#1088 Remove unused code
  src/main/java/org/dependencytrack/persistence/BomQueryManager.java
  src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java
  src/main/java/org/dependencytrack/persistence/FlushHelper.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/ServiceComponentQueryManager.java
  src/main/java/org/dependencytrack/persistence/VexQueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerableSoftwareQueryManager.java
  src/main/java/org/dependencytrack/util/HashUtil.java
  src/test/java/org/dependencytrack/persistence/FlushHelperTest.java
  src/test/java/org/dependencytrack/persistence/VulnerabilityQueryManagerTest.java
  src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  src/test/java/org/dependencytrack/util/HashUtilTest.java
Labels: technical debt

#1084 Add ability to get extension by name
  src/main/java/org/dependencytrack/plugin/NoSuchExtensionException.java
  src/main/java/org/dependencytrack/plugin/PluginManager.java
  src/test/java/org/dependencytrack/plugin/PluginManagerTest.java
Labels: enhancement

#1089 Fix component occurrences and properties not being cloned
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: defect

#1096 Remove `properties` from `Project`'s default fetch group
  src/main/java/org/dependencytrack/model/Project.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: enhancement

#1103 Improve efficiency of `is_dependency_of` and `is_exclusive_dependency_of` CEL functions
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
Labels: enhancement

#1093 Prevent duplicates in `PROJECT_ACCESS_TEAMS` table
  src/main/java/org/dependencytrack/model/Project.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/main/resources/migration/changelog-v5.6.0.xml
  src/test/java/org/dependencytrack/ResourceTest.java
  src/test/java/org/dependencytrack/persistence/datanucleus/method/ProjectIsAccessibleByMethodTest.java
  src/test/java/org/dependencytrack/resources/v1/AccessControlResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/BadgeResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: defect

#1104 Use advisory lock for BOM processing task instead of Shedlock
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  src/test/java/org/dependencytrack/persistence/QueryManagerTest.java
Labels: defect

#1090 Refactor FindingsQueryManager and FindingsSearchQueryManager to use JDBI
  src/main/java/org/dependencytrack/integrations/kenna/KennaDataTransformer.java
  src/main/java/org/dependencytrack/model/Finding.java
  src/main/java/org/dependencytrack/model/GroupedFinding.java
  src/main/java/org/dependencytrack/model/Severity.java
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXExporter.java
  src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java
  src/main/java/org/dependencytrack/persistence/FindingsSearchQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/jdbi/FindingDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/RepositoryMetaDao.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/main/java/org/dependencytrack/tasks/VulnerabilityManagementUploadTask.java
  src/main/resources/templates/findings/sarif.peb
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/integrations/FindingPackagingFormatTest.java
  src/test/java/org/dependencytrack/integrations/defectdojo/DefectDojoUploaderTest.java
  src/test/java/org/dependencytrack/model/FindingTest.java
  src/test/java/org/dependencytrack/model/GroupedFindingTest.java
  src/test/java/org/dependencytrack/persistence/ProjectQueryManagerTest.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: enhancement, technical debt

#1105 refactor: DefaultObjectGenerator shared QueryManager instance
  src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
Labels: enhancement

#1106 Update findings `cwes` mapping
  src/main/java/org/dependencytrack/model/Finding.java
  src/main/resources/templates/findings/sarif.peb
  src/test/java/org/dependencytrack/model/FindingTest.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: defect

#1087 Materialize project hierarchies in separate table
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/resources/migration/changelog-v5.6.0.xml
  src/main/resources/migration/procedures/function_has-project-access.sql
  src/test/java/org/dependencytrack/persistence/PolicyQueryManagerTest.java
  src/test/java/org/dependencytrack/persistence/ProjectHierarchyMaintenanceTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: enhancement

#1107 Raise minimum supported PostgreSQL version to 13
  dev/scripts/dbschema-generate-migration.sh
  dev/scripts/dbschema-generate.sh
  src/main/java/org/dependencytrack/common/ConfigKey.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/PostgresTestContainer.java
  src/test/java/org/dependencytrack/persistence/migration/MigrationInitializerTest.java
  src/test/java/org/dependencytrack/persistence/migration/change/v530/RenameForeignKeysChangeTest.java
  src/test/java/org/dependencytrack/persistence/migration/change/v530/RenameNumberedIndexesChangeTest.java
  src/test/java/org/dependencytrack/persistence/migration/change/v550/ComputeSeveritiesChangeTest.java
Labels: technical debt
