Repository DependencyTrack/hyades-apiserver, pull requests merged in 2025-08, with the labels that each got.

#1361 Require `VULNERABILITY_ANALYSIS` permission for project reanalysis
  apiserver/src/main/java/org/dependencytrack/resources/v1/FindingResource.java
Labels: defect

#1360 Issue-1822 : Fix deletion of dependency metrics by component IDs
  apiserver/src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
Labels: defect

#1342 Add project's components endpoint to API v2
  api/src/main/openapi/components/schemas/external-reference.yaml
  api/src/main/openapi/components/schemas/hashes.yaml
  api/src/main/openapi/components/schemas/license.yaml
  api/src/main/openapi/components/schemas/list-components-response-item.yaml
  api/src/main/openapi/components/schemas/list-components-response.yaml
  api/src/main/openapi/openapi.yaml
  api/src/main/openapi/paths/projects_uuid_components.yaml
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/ComponentDao.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/AbstractApiResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v2/ProjectsResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v2/exception/ProjectAccessDeniedExceptionMapper.java
  apiserver/src/main/java/org/dependencytrack/resources/v2/mapping/ModelMapper.java
  apiserver/src/test/java/org/dependencytrack/resources/v2/ProjectsResourceTest.java
  persistence-migration/src/main/resources/migration/changelog-main.xml
  persistence-migration/src/main/resources/migration/changelog-v5.7.0.xml
Labels: enhancement

#1383 Fix `/api/v1/project/clone` returning wrong workflow token
  apiserver/src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
Labels: defect

#1386 Issue-1837 : Log more details when timing out and failing workflow steps
  apiserver/src/main/java/org/dependencytrack/common/MdcKeys.java
  apiserver/src/main/java/org/dependencytrack/parser/dependencytrack/NotificationModelConverter.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDao.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/WorkflowDao.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/mapping/NotificationProjectRowMapper.java
  apiserver/src/main/java/org/dependencytrack/tasks/maintenance/WorkflowMaintenanceTask.java
  apiserver/src/test/java/org/dependencytrack/event/kafka/processor/ProcessedVulnerabilityScanResultProcessorTest.java
  apiserver/src/test/java/org/dependencytrack/parser/dependencytrack/NotificationModelConverterTest.java
  apiserver/src/test/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDaoTest.java
  proto/src/main/proto/org/dependencytrack/notification/v1/notification.proto
Labels: defect

#1391 Pin digests of all GitHub Actions
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-publish.yaml
  .github/workflows/ci-release.yaml
  .github/workflows/ci-test-pr-coverage.yml
  .github/workflows/ci-test.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/lock.yaml
Labels: dependencies
