Repository DependencyTrack/hyades-apiserver, pull requests merged in 2025-06, with the labels that each got.

#1244 Use fixed ports for dev services containers
  apiserver/src/main/java/org/dependencytrack/common/ConfigKey.java
  apiserver/src/main/java/org/dependencytrack/dev/DevServicesInitializer.java
  apiserver/src/main/resources/application.properties
  coverage-report/pom.xml
Labels: enhancement, dx

#1250 Fix file storage package name
  apiserver/src/main/java/org/dependencytrack/event/BomUploadEvent.java
  apiserver/src/main/java/org/dependencytrack/filestorage/FileStorage.java
  apiserver/src/main/java/org/dependencytrack/filestorage/FileStoragePlugin.java
  apiserver/src/main/java/org/dependencytrack/filestorage/LocalFileStorage.java
  apiserver/src/main/java/org/dependencytrack/filestorage/LocalFileStorageFactory.java
  apiserver/src/main/java/org/dependencytrack/filestorage/MemoryFileStorage.java
  apiserver/src/main/java/org/dependencytrack/filestorage/MemoryFileStorageFactory.java
  apiserver/src/main/java/org/dependencytrack/filestorage/S3FileStorage.java
  apiserver/src/main/java/org/dependencytrack/filestorage/S3FileStorageFactory.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/BomResource.java
  apiserver/src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
  apiserver/src/main/resources/META-INF/services/org.dependencytrack.plugin.api.ExtensionPointMetadata
  apiserver/src/main/resources/META-INF/services/org.dependencytrack.plugin.api.Plugin
  apiserver/src/test/java/org/dependencytrack/event/BomUploadEventTest.java
  apiserver/src/test/java/org/dependencytrack/filestorage/LocalFileStorageTest.java
  apiserver/src/test/java/org/dependencytrack/filestorage/MemoryFileStorageTest.java
  apiserver/src/test/java/org/dependencytrack/filestorage/S3FileStorageTest.java
  apiserver/src/test/java/org/dependencytrack/plugin/PluginManagerTest.java
  apiserver/src/test/java/org/dependencytrack/policy/cel/CelPolicyEngineTest.java
  apiserver/src/test/java/org/dependencytrack/tasks/BomUploadProcessingTaskTest.java
  proto/src/main/proto/org/dependencytrack/filestorage/v1/filestorage.proto
  proto/src/main/proto/org/dependencytrack/storage/v1alpha1/storage.proto
Labels: technical debt

#1252 Remove watchdog logging
  alpine/alpine-common/src/main/java/alpine/Config.java
  alpine/alpine-server/src/main/java/alpine/server/AlpineServlet.java
  apiserver/src/main/resources/application.properties
  apiserver/src/test/resources/integration/application-h2.properties
  apiserver/src/test/resources/integration/application-mysql.properties
  apiserver/src/test/resources/integration/application-postgres.properties
Labels: technical debt

#1232 Convert projects bulk-fetch DN queries to JDBI
  apiserver/src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/QueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizer.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/ProjectDao.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/mapping/OrganizationalEntityMapper.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/AccessControlResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  apiserver/src/test/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizerTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/AccessControlResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/exception/NotSortableExceptionMapperTest.java
  apiserver/src/test/java/org/dependencytrack/tasks/maintenance/ProjectMaintenanceTaskTest.java
Labels: enhancement

#1255 Ingest datanucleus-postgresql plugin
  alpine/pom.xml
  apiserver/pom.xml
  coverage-report/pom.xml
  pom.xml
  support/datanucleus-plugin/plugin/pom.xml
  support/datanucleus-plugin/plugin/src/main/java/org/dependencytrack/support/datanucleus/method/AbstractJsonbMethod.java
  support/datanucleus-plugin/plugin/src/main/java/org/dependencytrack/support/datanucleus/method/JsonbContainsMethod.java
  support/datanucleus-plugin/plugin/src/main/java/org/dependencytrack/support/datanucleus/method/JsonbOperators.java
  support/datanucleus-plugin/plugin/src/main/java/org/dependencytrack/support/datanucleus/valuegenerator/UUIDv7Generator.java
  support/datanucleus-plugin/plugin/src/main/resources/plugin.xml
  support/datanucleus-plugin/pom.xml
  support/datanucleus-plugin/test/pom.xml
  support/datanucleus-plugin/test/src/main/java/org/dependencytrack/support/datanucleus/test/Person.java
  support/datanucleus-plugin/test/src/main/resources/META-INF/persistence.xml
  support/datanucleus-plugin/test/src/main/resources/schema.sql
  support/datanucleus-plugin/test/src/test/java/org/dependencytrack/support/datanucleus/AbstractTest.java
  support/datanucleus-plugin/test/src/test/java/org/dependencytrack/support/datanucleus/method/JsonbContainsMethodTest.java
  support/datanucleus-plugin/test/src/test/java/org/dependencytrack/support/datanucleus/valuegenerator/UUIDv7GeneratorTest.java
Labels: enhancement

#1274 Add index on "PROJECT"."INACTIVE_SINCE"
  persistence-migration/src/main/resources/migration/changelog-v5.6.0.xml
Labels: enhancement

#1275 Fix build failures when using dev services
  apiserver/pom.xml
Labels: defect, dx

#1283 Add pagination to `/api/v1/team` -> `getTeams`
  alpine/alpine-infra/src/main/java/alpine/persistence/AlpineQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  apiserver/src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
Labels: enhancement

#1277 Add explicit permission to bypass project access checks
  apiserver/src/main/java/org/dependencytrack/auth/Permissions.java
  apiserver/src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizer.java
  apiserver/src/test/java/org/dependencytrack/auth/PermissionsTest.java
  apiserver/src/test/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizerTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
  persistence-migration/src/main/resources/migration/changelog-v5.6.0.xml
Labels: enhancement

#1278 Inline project access check
  .mvn/maven-build-cache-config.xml
  apiserver/src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/QueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/datanucleus/method/ProjectIsAccessibleByMethod.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizer.java
  apiserver/src/test/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizerTest.java
  persistence-jooq/src/main/java/org/dependencytrack/persistence/jooq/generated/Indexes.java
  persistence-jooq/src/main/java/org/dependencytrack/persistence/jooq/generated/Routines.java
  persistence-jooq/src/main/java/org/dependencytrack/persistence/jooq/generated/tables/DependencyMetrics.java
  persistence-jooq/src/main/java/org/dependencytrack/persistence/jooq/generated/tables/Project.java
  persistence-migration/src/main/resources/migration/procedures/function_has-project-access.sql
  persistence-migration/src/main/resources/migration/procedures/function_has-user-project-access.sql
Labels: enhancement

#1266 Handle conflict when creating teams via REST API
  apiserver/src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/problems/TeamAlreadyExistsProblemDetails.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
Labels: defect

#1294 Allow OIDC teams claim to be comma-delimited string
  alpine/alpine-server/src/main/java/alpine/server/auth/DefaultOidcAuthenticationCustomizer.java
  alpine/alpine-server/src/main/java/alpine/server/auth/OidcAuthenticationService.java
  alpine/alpine-server/src/test/java/alpine/server/auth/DefaultOidcAuthenticationCustomizerTest.java
  apiserver/src/main/resources/application.properties
Labels: enhancement
