Repository DependencyTrack/hyades-apiserver, pull requests merged in 2025-04, with the labels that each got.

#1110 Add USER_PROJECT_EFFECTIVE_PERMISSIONS table
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/jdbi/EffectivePermissionDao.java
  src/main/resources/migration/changelog-v5.6.0.xml
  src/test/java/org/dependencytrack/persistence/QueryManagerTest.java
Labels: enhancement

#1117 Ensure no duplicate entries in join tables
  src/main/java/org/dependencytrack/model/NotificationRule.java
  src/main/java/org/dependencytrack/resources/v1/NotificationRuleResource.java
  src/main/resources/migration/changelog-v5.6.0.xml
  src/test/java/org/dependencytrack/model/NotificationRuleTest.java
  src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java
Labels: enhancement

#1108 Refactor `Analysis` DN queries to JDBI
  src/main/java/org/dependencytrack/event/kafka/KafkaEventDispatcher.java
  src/main/java/org/dependencytrack/model/Analysis.java
  src/main/java/org/dependencytrack/parser/cyclonedx/CycloneDXVexImporter.java
  src/main/java/org/dependencytrack/persistence/AnalysisQueryManager.java
  src/main/java/org/dependencytrack/persistence/FindingsQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  src/main/java/org/dependencytrack/persistence/jdbi/AnalysisDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/ComponentDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/ProjectDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityDao.java
  src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
  src/main/java/org/dependencytrack/util/AnalysisCommentUtil.java
  src/main/java/org/dependencytrack/util/NotificationUtil.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
  src/test/java/org/dependencytrack/parser/cyclonedx/CycloneDXVexImporterTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/AnalysisDaoTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/ComponentDaoTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/NotificationSubjectDaoTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/ProjectDaoTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/VulnerabilityDaoTest.java
  src/test/java/org/dependencytrack/resources/v1/AnalysisResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/BomResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VexResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
  src/test/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTaskTest.java
  src/test/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTaskTest.java
Labels: enhancement

#1116 Fix v5.6.0 migration failing when projects without parent exist
  src/main/resources/migration/changelog-v5.6.0.xml
Labels: defect

#1118 Improve efficiency of retention queries
  src/main/java/org/dependencytrack/persistence/jdbi/MetricsDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/VulnerabilityScanDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/WorkflowDao.java
Labels: enhancement

#1111 Add pagination to `/api/v1/finding` endpoints
  src/main/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizer.java
  src/main/java/org/dependencytrack/persistence/jdbi/FindingDao.java
  src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  src/test/java/org/dependencytrack/integrations/FindingPackagingFormatTest.java
  src/test/java/org/dependencytrack/model/FindingTest.java
  src/test/java/org/dependencytrack/model/GroupedFindingTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizerTest.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: enhancement, breaking change

#1120 Collect latency metrics of SQL queries executed via JDBI
  src/main/java/org/dependencytrack/persistence/jdbi/JdbiAttributes.java
  src/main/java/org/dependencytrack/persistence/jdbi/JdbiFactory.java
  src/main/java/org/dependencytrack/persistence/jdbi/QueryTimingSqlLogger.java
  src/main/java/org/dependencytrack/policy/cel/CelCommonPolicyLibrary.java
  src/main/java/org/dependencytrack/tasks/InternalComponentIdentificationTask.java
  src/test/java/org/dependencytrack/persistence/jdbi/QueryTimingSqlLoggerTest.java
Labels: enhancement

#1122 Add `severity` as postgres enum `type`
  src/main/java/org/dependencytrack/model/Analysis.java
  src/main/java/org/dependencytrack/model/Vulnerability.java
  src/main/java/org/dependencytrack/persistence/jdbi/FindingDao.java
  src/main/resources/migration/changelog-v5.6.0.xml
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: enhancement

#1126 Prevent duplicate OIDC groups
  src/main/resources/migration/changelog-v5.6.0.xml
Labels: defect

#1125 Disable DataNucleus bulk-fetching for list operations on `Project`
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
Labels: defect

#1133 Refactor metrics queries to use JDBI
  apiserver/src/main/java/org/dependencytrack/model/DependencyMetrics.java
  apiserver/src/main/java/org/dependencytrack/model/ProjectMetrics.java
  apiserver/src/main/java/org/dependencytrack/persistence/MetricsQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/QueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/MetricsDao.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/ProjectDao.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/AbstractApiResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/MetricsResource.java
  apiserver/src/test/java/org/dependencytrack/persistence/jdbi/MetricsDaoTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/MetricsResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: enhancement

#1134 Port: Upgrade to Alpine 3.2.0 and handle API key migration
  apiserver/pom.xml
  apiserver/src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  apiserver/src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizer.java
  apiserver/src/main/java/org/dependencytrack/persistence/migration/change/v560/ApiKeyMigrationChange.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  apiserver/src/main/resources/migration/changelog-v5.6.0.xml
  apiserver/src/test/java/org/dependencytrack/ResourceTest.java
  apiserver/src/test/java/org/dependencytrack/persistence/QueryManagerTest.java
  apiserver/src/test/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizerTest.java
  apiserver/src/test/java/org/dependencytrack/persistence/migration/change/v560/ApiKeyMigrationChangeTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/OidcResourceAuthenticatedTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/PolicyViolationResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/UserResourceAuthenticatedTest.java
  apiserver/src/test/resources/migration/custom/ApiKeyMigrationChangeTest-changelog.xml
  apiserver/src/test/resources/migration/custom/ApiKeyMigrationChangeTest-schema.sql
Labels: enhancement, v4-port

#1130 Convert to multi-module Maven project (phase 2.1)
  .github/workflows/buf.yml
  .github/workflows/ci-test-pr-coverage.yml
  .github/workflows/ci-test.yaml
  .idea/runConfigurations/Build API Server.run.xml
  apiserver/pom.xml
  apiserver/src/test/java/org/dependencytrack/util/ConfigUtilTest.java
  coverage-report/pom.xml
  pom.xml
  proto/pom.xml
  proto/src/main/proto/buf.yaml
  proto/src/main/proto/org/cyclonedx/v1_6/cyclonedx.proto
  proto/src/main/proto/org/dependencytrack/mirror/v1/epss_data.proto
  proto/src/main/proto/org/dependencytrack/notification/v1/notification.proto
  proto/src/main/proto/org/dependencytrack/policy/v1/policy.proto
  proto/src/main/proto/org/dependencytrack/repometaanalysis/v1/repo_meta_analysis.proto
  proto/src/main/proto/org/dependencytrack/storage/v1alpha1/storage.proto
  proto/src/main/proto/org/dependencytrack/vulnanalysis/v1/vuln_analysis.proto
Labels: enhancement

#1136 refactor: user/permission resource for bulk request
  apiserver/src/main/java/org/dependencytrack/resources/v1/PermissionResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/UserResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/problems/AccessManagementProblemDetails.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/problems/ProblemDetails.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/vo/TeamPermissionsSetRequest.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/vo/TeamsSetRequest.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/vo/UserPermissionsSetRequest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/UserResourceAuthenticatedTest.java
Labels: enhancement

#1150 Support for extra JWT custom claims
  alpine/alpine-server/src/main/java/alpine/server/auth/JsonWebToken.java
Labels: enhancement

#1149 Add OidcAuthenticationCustomizer service provider interface
  alpine/alpine-common/src/main/java/alpine/Config.java
  alpine/alpine-server/src/main/java/alpine/server/auth/DefaultOidcAuthenticationCustomizer.java
  alpine/alpine-server/src/main/java/alpine/server/auth/OidcAuthenticationCustomizer.java
  alpine/alpine-server/src/main/java/alpine/server/auth/OidcAuthenticationService.java
  alpine/alpine-server/src/main/java/alpine/server/auth/OidcProfile.java
  alpine/alpine-server/src/main/resources/META-INF/services/alpine.server.auth.OidcAuthenticationCustomizer
Labels: enhancement

#1151 Use HikariCP for DB connection pooling in tests
  apiserver/src/test/java/org/dependencytrack/PersistenceCapableTest.java
  apiserver/src/test/java/org/dependencytrack/persistence/jdbi/JdbiFactoryTest.java
Labels: defect

#1144 Update Alpine JDO metadata to reflect DB schema changes
  alpine/alpine-model/src/main/java/alpine/model/ApiKey.java
  alpine/alpine-model/src/main/java/alpine/model/LdapUser.java
  alpine/alpine-model/src/main/java/alpine/model/ManagedUser.java
  alpine/alpine-model/src/main/java/alpine/model/MappedLdapGroup.java
  alpine/alpine-model/src/main/java/alpine/model/MappedOidcGroup.java
  alpine/alpine-model/src/main/java/alpine/model/OidcUser.java
  alpine/alpine-model/src/main/java/alpine/model/Team.java
  apiserver/src/main/resources/META-INF/package.jdo
Labels: technical debt

#1159 Migrate to maintained protobuf-maven-plugin
  proto/pom.xml
Labels: technical debt
