Repository DependencyTrack/hyades-apiserver, pull requests merged in 2025-05, with the labels that each got.

#1165 Ensure all GitHub workflows have a timeout
  .github/workflows/_meta-build.yaml
  .github/workflows/ci-publish.yaml
  .github/workflows/ci-release.yaml
  .github/workflows/ci-test-pr-coverage.yml
  .github/workflows/ci-test.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/lock.yaml
  .github/workflows/mirror-container-image.yml
Labels: enhancement

#1186 Add `hasOccurrences` in `/api/v1/finding` responses
  apiserver/src/main/java/org/dependencytrack/model/Finding.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/FindingDao.java
  apiserver/src/test/java/org/dependencytrack/integrations/FindingPackagingFormatTest.java
  apiserver/src/test/java/org/dependencytrack/integrations/defectdojo/DefectDojoUploaderTest.java
  apiserver/src/test/java/org/dependencytrack/model/FindingTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: enhancement

#1169 Consolidate user tables
  alpine/alpine-infra/src/main/java/alpine/persistence/AlpineQueryManager.java
  alpine/alpine-model/src/main/java/alpine/model/ApiKey.java
  alpine/alpine-model/src/main/java/alpine/model/LdapUser.java
  alpine/alpine-model/src/main/java/alpine/model/ManagedUser.java
  alpine/alpine-model/src/main/java/alpine/model/OidcUser.java
  alpine/alpine-model/src/main/java/alpine/model/Permission.java
  alpine/alpine-model/src/main/java/alpine/model/Team.java
  alpine/alpine-model/src/main/java/alpine/model/User.java
  alpine/alpine-model/src/main/java/alpine/model/UserPrincipal.java
  alpine/alpine-model/src/main/resources/META-INF/persistence.xml
  alpine/alpine-server/src/main/java/alpine/server/filters/AuthorizationFilter.java
  alpine/alpine-server/src/main/java/alpine/server/resources/AlpineResource.java
  alpine/alpine-server/src/test/java/alpine/server/auth/JwtAuthenticationServiceTest.java
  apiserver/src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/QueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/EffectivePermissionDao.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/AnalysisResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/BadgeResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/PermissionResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/TeamResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/UserResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/ViolationAnalysisResource.java
  apiserver/src/main/java/org/dependencytrack/util/PrincipalUtil.java
  apiserver/src/main/resources/migration/changelog-v5.6.0.xml
  apiserver/src/test/java/org/dependencytrack/persistence/QueryManagerTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/PermissionResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/TeamResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/UserResourceAuthenticatedTest.java
Labels: enhancement

#1189 Include Alpine JDO classes in `persistence.xml` of API Server
  apiserver/src/main/resources/META-INF/persistence.xml
Labels: defect

#1202 Add `hasAnalysis` parameter in project findings endpoint
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/FindingDao.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/FindingResource.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
Labels: enhancement

#1141 Partition metrics tables
  apiserver/src/main/java/org/dependencytrack/metrics/Metrics.java
  apiserver/src/main/java/org/dependencytrack/model/DependencyMetrics.java
  apiserver/src/main/java/org/dependencytrack/model/PortfolioMetrics.java
  apiserver/src/main/java/org/dependencytrack/model/ProjectMetrics.java
  apiserver/src/main/java/org/dependencytrack/persistence/ComponentQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/DefaultObjectGenerator.java
  apiserver/src/main/java/org/dependencytrack/persistence/MetricsQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/QueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/MetricsDao.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/BadgeResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/MetricsResource.java
  apiserver/src/main/java/org/dependencytrack/tasks/maintenance/MetricsMaintenanceTask.java
  apiserver/src/main/resources/META-INF/persistence.xml
  apiserver/src/main/resources/application.properties
  apiserver/src/main/resources/migration/changelog-v5.6.0.xml
  apiserver/src/main/resources/migration/procedures/procedure_update-component-metrics.sql
  apiserver/src/main/resources/migration/procedures/procedure_update-portfolio-metrics.sql
  apiserver/src/main/resources/migration/procedures/procedure_update-project-metrics.sql
  apiserver/src/test/java/org/dependencytrack/model/DependencyMetricsTest.java
  apiserver/src/test/java/org/dependencytrack/model/PortfolioMetricsTest.java
  apiserver/src/test/java/org/dependencytrack/model/ProjectMetricsTest.java
  apiserver/src/test/java/org/dependencytrack/persistence/DefaultObjectGeneratorTest.java
  apiserver/src/test/java/org/dependencytrack/persistence/jdbi/ComponentDaoTest.java
  apiserver/src/test/java/org/dependencytrack/persistence/jdbi/MetricsDaoTest.java
  apiserver/src/test/java/org/dependencytrack/persistence/jdbi/MetricsTestDao.java
  apiserver/src/test/java/org/dependencytrack/persistence/jdbi/ProjectDaoTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/MetricsResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  apiserver/src/test/java/org/dependencytrack/tasks/maintenance/MetricsMaintenanceTaskTest.java
  apiserver/src/test/java/org/dependencytrack/tasks/metrics/ComponentMetricsUpdateTaskTest.java
  apiserver/src/test/java/org/dependencytrack/tasks/metrics/PortfolioMetricsUpdateTaskTest.java
  apiserver/src/test/java/org/dependencytrack/tasks/metrics/ProjectMetricsUpdateTaskTest.java
Labels: enhancement

#1124 Ensure tag name and relationship uniqueness
  apiserver/src/main/java/org/dependencytrack/integrations/kenna/KennaDataTransformer.java
  apiserver/src/main/java/org/dependencytrack/model/NotificationRule.java
  apiserver/src/main/java/org/dependencytrack/model/Policy.java
  apiserver/src/main/java/org/dependencytrack/model/Project.java
  apiserver/src/main/java/org/dependencytrack/model/Tag.java
  apiserver/src/main/java/org/dependencytrack/model/Vulnerability.java
  apiserver/src/main/java/org/dependencytrack/parser/dependencytrack/NotificationModelConverter.java
  apiserver/src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/QueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/VulnerabilityQueryManager.java
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/mapping/VulnerabilityRowMapper.java
  apiserver/src/main/java/org/dependencytrack/policy/cel/CelPolicyQueryManager.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/VulnerabilityResource.java
  apiserver/src/main/java/org/dependencytrack/util/NotificationUtil.java
  apiserver/src/main/resources/migration/changelog-v5.6.0.xml
  apiserver/src/test/java/org/dependencytrack/model/PolicyTest.java
  apiserver/src/test/java/org/dependencytrack/model/TagTest.java
  apiserver/src/test/java/org/dependencytrack/parser/dependencytrack/NotificationModelConverterTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/NotificationRuleResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/VulnerabilityResourceTest.java
Labels: defect

#1177 Decouple Liquibase migrations into their own module
  alpine/pom.xml
  apiserver/pom.xml
  apiserver/src/main/java/org/dependencytrack/persistence/MigrationInitializer.java
  apiserver/src/main/java/org/dependencytrack/persistence/migration/change/v550/ComputeSeveritiesChange.java
  apiserver/src/main/webapp/WEB-INF/web.xml
  apiserver/src/test/java/org/dependencytrack/PostgresTestContainer.java
  apiserver/src/test/java/org/dependencytrack/persistence/MigrationInitializerTest.java
  coverage-report/pom.xml
  dev/scripts/dbschema-generate-migration.sh
  dev/scripts/dbschema-generate.sh
  persistence-migration/pom.xml
  persistence-migration/src/main/java/org/dependencytrack/persistence/migration/LiquibaseLogger.java
  persistence-migration/src/main/java/org/dependencytrack/persistence/migration/MigrationExecutor.java
  persistence-migration/src/main/java/org/dependencytrack/persistence/migration/change/v530/RenameForeignKeysChange.java
  persistence-migration/src/main/java/org/dependencytrack/persistence/migration/change/v530/RenameNumberedIndexesChange.java
  persistence-migration/src/main/java/org/dependencytrack/persistence/migration/change/v550/ComputeSeveritiesChange.java
  persistence-migration/src/main/java/org/dependencytrack/persistence/migration/change/v560/ApiKeyMigrationChange.java
  persistence-migration/src/main/resources/migration/changelog-main.xml
  persistence-migration/src/main/resources/migration/changelog-procedures.xml
  persistence-migration/src/main/resources/migration/changelog-v5.3.0.xml
  persistence-migration/src/main/resources/migration/changelog-v5.4.0.xml
  persistence-migration/src/main/resources/migration/changelog-v5.5.0.xml
  persistence-migration/src/main/resources/migration/changelog-v5.6.0.xml
  persistence-migration/src/main/resources/migration/procedures/function_calc-risk-score.sql
  persistence-migration/src/main/resources/migration/procedures/function_has-project-access.sql
  persistence-migration/src/main/resources/migration/procedures/function_jsonb-vuln-aliases.sql
  persistence-migration/src/main/resources/migration/procedures/procedure_update-component-metrics.sql
  persistence-migration/src/main/resources/migration/procedures/procedure_update-portfolio-metrics.sql
  persistence-migration/src/main/resources/migration/procedures/procedure_update-project-metrics.sql
  persistence-migration/src/test/java/org/dependencytrack/persistence/migration/MigrationExecutorTest.java
  persistence-migration/src/test/java/org/dependencytrack/persistence/migration/change/v530/RenameForeignKeysChangeTest.java
  persistence-migration/src/test/java/org/dependencytrack/persistence/migration/change/v530/RenameNumberedIndexesChangeTest.java
  persistence-migration/src/test/java/org/dependencytrack/persistence/migration/change/v550/ComputeSeveritiesChangeTest.java
  persistence-migration/src/test/java/org/dependencytrack/persistence/migration/change/v560/ApiKeyMigrationChangeTest.java
  persistence-migration/src/test/resources/org/dependencytrack/persistence/migration/change/ApiKeyMigrationChangeTest-changelog.xml
  persistence-migration/src/test/resources/org/dependencytrack/persistence/migration/change/ApiKeyMigrationChangeTest-schema.sql
  persistence-migration/src/test/resources/org/dependencytrack/persistence/migration/change/ComputeSeveritiesChangeTest-changelog.xml
  persistence-migration/src/test/resources/org/dependencytrack/persistence/migration/change/ComputeSeveritiesChangeTest-schema.sql
  persistence-migration/src/test/resources/org/dependencytrack/persistence/migration/change/RenameForeignKeysChangeTest-changelog.xml
  persistence-migration/src/test/resources/org/dependencytrack/persistence/migration/change/RenameNumberedIndexesChangeTest-changelog.xml
  persistence-migration/src/test/resources/org/dependencytrack/persistence/migration/change/schema-v5.2.0-postgresql.sql
  pom.xml
Labels: enhancement

#1187 Introduce jOOQ
  persistence-jooq/pom.xml
  pom.xml
Labels: enhancement

#1209 Add jOOQ DSLContext factory
  apiserver/pom.xml
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/JdbiFactory.java
  apiserver/src/main/java/org/dependencytrack/persistence/jooq/DslContextFactory.java
  apiserver/src/main/java/org/dependencytrack/util/PersistenceUtil.java
  apiserver/src/test/java/org/dependencytrack/persistence/jooq/DslContextFactoryTest.java
Labels: enhancement

#1216 Update DataNucleus enhance commands to include alpine-model module
  .idea/runConfigurations/DataNucleus Enhance.run.xml
  DEVELOPING.md
  apiserver/pom.xml
Labels: enhancement, dx

#1221 Fix failing `v5.6.0-17` migration for deployments with duplicate `TEAM` records
  persistence-migration/src/main/resources/migration/changelog-v5.6.0.xml
Labels: defect

#1222 Fix failing `v5.6.0-23` migration for deployments with duplicate usernames
  persistence-migration/src/main/resources/migration/changelog-v5.6.0.xml
Labels: defect
