Repository DependencyTrack/hyades-apiserver, pull requests merged in 2025-07, with the labels that each got.

#1305 Address dependency convergence using Maven BOMs
  alpine/alpine-executable-war/pom.xml
  alpine/pom.xml
  apiserver/pom.xml
  pom.xml
Labels: enhancement, dependencies

#1302 Don't generate public/private key pair anymore
  alpine/alpine-common/src/main/java/alpine/Config.java
  alpine/alpine-infra/src/main/java/alpine/security/crypto/KeyManager.java
  alpine/alpine-infra/src/test/java/alpine/security/crypto/KeyManagerTest.java
  apiserver/src/main/resources/application.properties
Labels: technical debt

#1320 Various REST API v2 fixes
  apiserver/src/main/java/org/dependencytrack/resources/v2/MetricsResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v2/OpenApiResource.java
  apiserver/src/main/java/org/dependencytrack/resources/v2/TeamsResource.java
  apiserver/src/test/java/org/dependencytrack/resources/v2/MetricsResourceTest.java
  apiserver/src/test/java/org/dependencytrack/resources/v2/WorkflowsResourceTest.java
Labels: defect

#1321 Add `version` filter to concise project endpoint
  apiserver/src/main/java/org/dependencytrack/persistence/jdbi/ProjectDao.java
  apiserver/src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  apiserver/src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: enhancement

#1326 Remove recursive parent ref from workflow states response
  api/src/main/openapi/components/schemas/list-workflow-states-response-item.yaml
  apiserver/src/main/java/org/dependencytrack/resources/v2/WorkflowsResource.java
Labels: enhancement

#1327 Enable OpenAPI breaking change detection workflow
  .github/workflows/ci-openapi.yaml
Labels: enhancement

#1328 Fix `next` page URL generation
  apiserver/src/main/java/org/dependencytrack/persistence/pagination/PageUtil.java
Labels: defect

#1337 Fix HikariCP failure to create meter registry
  alpine/alpine-server/src/main/java/alpine/server/persistence/PersistenceManagerFactory.java
Labels: defect

#1339 Use `project.version` to refer to submodules
  alpine/alpine-infra/pom.xml
  alpine/alpine-model/pom.xml
  alpine/alpine-server/pom.xml
  apiserver/pom.xml
  coverage-report/pom.xml
  persistence-migration/pom.xml
  pom.xml
  support/datanucleus-plugin/test/pom.xml
Labels: technical debt

#1343 Fix glibc compatibility of Docker image
  apiserver/src/main/docker/Dockerfile
Labels: defect

#1344 Try to fix flaky `ProcessorManagerTest`
  apiserver/src/test/java/org/dependencytrack/event/kafka/processor/api/ProcessorManagerTest.java
Labels: technical debt
