Repository DependencyTrack/hyades-apiserver, pull requests merged in 2025-02, with the labels that each got.

#1049 Fix failures during BOM processing not being logged
  src/main/java/org/dependencytrack/tasks/BomUploadProcessingTask.java
Labels: defect

#1042 Port : Fix REST endpoints for adding tags
  src/main/java/org/dependencytrack/persistence/NotificationQueryManager.java
  src/main/java/org/dependencytrack/persistence/PolicyQueryManager.java
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/TagQueryManager.java
  src/main/java/org/dependencytrack/resources/v1/ProjectResource.java
  src/test/java/org/dependencytrack/resources/v1/TagResourceTest.java
Labels: defect, v4-port

#1053 Issue 1600 : Add scheduled task for project retention maintenance
  src/main/java/org/dependencytrack/event/EventSubsystemInitializer.java
  src/main/java/org/dependencytrack/event/maintenance/ProjectMaintenanceEvent.java
  src/main/java/org/dependencytrack/model/ConfigPropertyConstants.java
  src/main/java/org/dependencytrack/persistence/jdbi/ConfigPropertyDao.java
  src/main/java/org/dependencytrack/persistence/jdbi/ProjectDao.java
  src/main/java/org/dependencytrack/tasks/TaskScheduler.java
  src/main/java/org/dependencytrack/tasks/maintenance/ProjectMaintenanceTask.java
  src/main/resources/application.properties
  src/test/java/org/dependencytrack/tasks/maintenance/ProjectMaintenanceTaskTest.java
Labels: enhancement

#1058 Fix `DbUtil` not being initialized
  src/main/java/org/dependencytrack/persistence/migration/MigrationInitializer.java
  src/test/java/org/dependencytrack/PostgresTestContainer.java
Labels: defect

#1061 Mirror container images to Docker Hub
  .github/workflows/ci-build.yaml
  .github/workflows/ci-publish.yaml
  .github/workflows/mirror-container-image.yml
Labels: enhancement

#1062 Fix erroneous over-suppression of Snyk findings
  src/main/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessor.java
  src/test/java/org/dependencytrack/event/kafka/processor/VulnerabilityScanResultProcessorTest.java
Labels: defect

#1064 Log deleted project info + fix nullPointerException
  src/main/java/org/dependencytrack/persistence/jdbi/ProjectDao.java
  src/main/java/org/dependencytrack/tasks/maintenance/ProjectMaintenanceTask.java
  src/test/java/org/dependencytrack/tasks/maintenance/ProjectMaintenanceTaskTest.java
Labels: defect

#1060 Consider project hierarchies for portfolio ACL checks
  pom.xml
  src/main/java/org/dependencytrack/persistence/ProjectQueryManager.java
  src/main/java/org/dependencytrack/persistence/QueryManager.java
  src/main/java/org/dependencytrack/persistence/datanucleus/method/ProjectIsAccessibleByMethod.java
  src/main/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizer.java
  src/main/resources/META-INF/MANIFEST.MF
  src/main/resources/migration/changelog-procedures.xml
  src/main/resources/migration/procedures/function_has-project-access.sql
  src/main/resources/plugin.xml
  src/test/java/org/dependencytrack/persistence/datanucleus/method/ProjectIsAccessibleByMethodTest.java
  src/test/java/org/dependencytrack/persistence/jdbi/ApiRequestStatementCustomizerTest.java
  src/test/java/org/dependencytrack/resources/v1/FindingResourceTest.java
  src/test/java/org/dependencytrack/resources/v1/ProjectResourceTest.java
Labels: enhancement
